In [1]:
from langchain_ollama.llms import OllamaLLM
from langchain_core.prompts import ChatPromptTemplate
import pandas as pd
import os
from langchain_community.embeddings import OllamaEmbeddings
from langchain_core.documents import Document
from langchain_chroma import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.llms import Ollama # Import Ollama for the LLM

In [2]:
from langchain_ollama import OllamaLLM
from langchain_core.prompts import ChatPromptTemplate
import re
import os
from langchain.text_splitter import CharacterTextSplitter
from langchain_community.document_loaders import TextLoader
from langchain_chroma import Chroma
from langchain_ollama import OllamaLLM
import pandas as pd
from langchain_ollama import OllamaEmbeddings
import math
from langchain_text_splitters import RecursiveJsonSplitter
import pandas as pd
import os
from langchain_community.embeddings import OllamaEmbeddings
from langchain_core.documents import Document
from langchain_chroma import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.llms import Ollama # Import Ollama for the LLM
import pandas as pd

In [3]:
from langchain_community.document_loaders import JSONLoader

In [4]:
DB_LOCATION = "./protein_db_rag"
OLLAMA_EMBEDDING_MODEL = 'mxbai-embed-large' # Model for embeddings
OLLAMA_LLM_MODEL = 'llama3.2'

In [3]:
data_csv=pd.read_csv('2k_pdb.csv')
data_csv.fillna('is not available', inplace=True)
data_csv.to_csv('2k_input_data.pdb.csv',index=False)

C:\Users\rkuma\AppData\Local\Temp\ipykernel_12008\3242012565.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'is not available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data_csv.fillna('is not available', inplace=True)

In [33]:
data_csv.iloc[0,0]

'100D'

In [7]:
data_csv.columns

Index(['rcsb_id', 'pubmed_id', 'title', 'PubMed Abstract',
       'Experimental Method', 'length_a', 'length_b', 'length_c',
       'angle_alpha', 'angle_beta', 'angle_gamma', 'space_group_name_H_M',
       'ls_d_res_high', 'ls_R_factor_R_work', 'ls_R_factor_R_free',
       'ls_R_factor_obs', 'Ligand_name', 'lig_formula', 'lig_inchi',
       'UniProt_id', 'source_organism', 'Molecule', 'poly_type',
       'poly_rcsb_entity_polymer_type', 'poly_pdbx_seq_one_letter_code_can',
       'poly_rcsb_sample_sequence_length', 'mutation', 'chain', 'num_chain',
       'relese_date'],
      dtype='object')

In [ ]:
['rcsb_id', 'pubmed_id', 'title', 'PubMed Abstract',
       'Experimental Method', 'length_a', 'length_b', 'length_c',
       'angle_alpha', 'angle_beta', 'angle_gamma', 'space_group_name_H_M',
       'ls_d_res_high', 'ls_R_factor_R_work', 'ls_R_factor_R_free',
       'ls_R_factor_obs', 'Ligand_name', 'lig_formula', 'lig_inchi',
       'UniProt_id', 'source_organism', 'Molecule', 'poly_type',
       'poly_rcsb_entity_polymer_type', 'poly_pdbx_seq_one_letter_code_can',
       'poly_rcsb_sample_sequence_length', 'mutation', 'chain', 'num_chain',
       'relese_date']

In [6]:
# data_csv5=data_csv.head(5)
input_data=data_csv
input_data.fillna('is not available', inplace=True)
list_csv=[]
for i in range(len(input_data)):
    dict_value={}
    for j in range(len(input_data.columns)):
        dict_value[input_data.columns[j]]=data_csv.iloc[i,j]
    list_csv.append(dict_value)

In [7]:
len(list_csv)

2000

In [37]:
input_data=data_csv.head(5)
input_data.fillna('is not available', inplace=True)
# input_data.columns
names=[]
for i in input_data.columns:
    j=i.replace('_',' ')
    names.append(j)

# print(input_data)
compl_data=[]
for i in range(len(input_data)):
    data_from_db=''
    for j in range(2,len(names)):
        # print(i,j,input_data.iloc[i,j])
        # print(i,j,input_data.iloc[i,j])
        # print(str(input_data),)
        data_from_db=f'{str(data_from_db)} {str(names[j])} is {str(input_data.iloc[i,j])} .'
    print(data_from_db)

 title is CRYSTAL STRUCTURE OF THE HIGHLY DISTORTED CHIMERIC DECAMER R(C)D(CGGCGCCG)R(G)-SPERMINE COMPLEX-SPERMINE BINDING TO PHOSPHATE ONLY AND MINOR GROOVE TERTIARY BASE-PAIRING . PubMed Abstract is The crystal structure of the self-complementary chimeric decamer duplex r(C)d(CGGCGCCG)r(G), with RNA base pairs at both termini, has been solved at 1.9 A resolution by the molecular replacement method and refined to an R value of 0.145 for 2,314 reflections. The C3'-endo sugar puckers of the terminal riboses apparently drive the entire chimeric duplex into an A-DNA conformation, in contrast to the B-DNA conformation adopted by the all-deoxy decamer of the same sequence. Five symmetry related duplexes encapsulate a spermine molecule which interacts with ten phosphate groups, both directly and through water molecules to form multiple ionic and hydrogen bonding interactions. The spermine interaction severely bends the duplexes by 31 degrees into the major groove at the fourth base pair G(4).C(17), jolts it and slides the 'base plate' into the minor groove. This base pair, together with the adjacent base pair in the top half and the corresponding pseudo two-fold related base pairs in the bottom half, form four minor groove base-paired multiples with the terminal base pairs of two neighboring duplexes. . Experimental Method is X-RAY DIFFRACTION . length a is 23.98 . length b is 40.77 . length c is 44.84 . angle alpha is 90.0 . angle beta is 90.0 . angle gamma is 90.0 . space group name H M is P 21 21 21 . ls d res high is 1.9 . ls R factor R work is 0.145 . ls R factor R free is is not available . ls R factor obs is 0.145 . Ligand name is ['SPERMINE'] . lig formula is ['C10 H26 N4'] . lig inchi is ['PFNFFQXMRSDOHW-UHFFFAOYSA-N'] . UniProt id is is not available . source organism is is not available . Molecule is is not available . poly type is polydeoxyribonucleotide/polyribonucleotide hybrid . poly rcsb entity polymer type is NA-hybrid . poly pdbx seq one letter code can is CCGGCGCCGG . poly rcsb sample sequence length is 10.0 . mutation is 0.0 . chain is ['A', 'B'] . num chain is 2 . relese date is 1994-12-05 .
 title is REFINEMENT OF NETROPSIN BOUND TO DNA: BIAS AND FEEDBACK IN ELECTRON DENSITY MAP INTERPRETATION . PubMed Abstract is The X-ray crystal structure of the complex of the B-DNA dodecamer CGCGAATTCGCG with the antitumor drug netropsin has been reexamined to locate the drug accurately for computer-based drug design. The optimum solution is with the drug centered in the AATT region of the minor groove, making three good bifurcated hydrogen bonds with adenine N3 and thymine O2 atoms along the floor of the groove. Pyrrole rings of netropsin are packed against the C2 positions of adenines, leaving no room for the amine group of guanine and, hence, providing a structural rationale for the A.T specificity of netropsin. An alternative positioning in which the drug is shifted along the minor groove by ca. one-half base pair step is rejected on the basis of free R factor calculations and the appearance of the original drug-free difference maps. Final omit maps, although of more pleasing appearance, are not a dependable means of discriminating between right and wrong structures. The shifted alternative drug position ignores potential hydrogen bonding along the floor of the groove, provides no explanation for netropsin's observed A.T specificity, and is contradicted by NMR results [Patel, D. J. (1982) Proc. Natl. Acad. Sci. U.S.A. 79, 6424]. . Experimental Method is X-RAY DIFFRACTION . length a is 24.27 . length b is 39.62 . length c is 63.57 . angle alpha is 90.0 . angle beta is 90.0 . angle gamma is 90.0 . space group name H M is P 21 21 21 . ls d res high is 2.25 . ls R factor R work is is not available . ls R factor R free is 0.252 . ls R factor obs is 0.163 . Ligand name is ['MAGNESIUM ION', 'NETROPSIN'] . lig formula is ['Mg', 'C18 H26 N10 O3'] . lig inchi is ['JLVVSXFLKOJNIY-UHFFFAOYSA-N', 'IDBIFFKSXLYUOT-UHFFFAOYSA-N'] . UniProt id is is not available . source organism is is not available . Molecule is is not available . poly type is polydeoxyribonucleotide . poly rcsb entity polymer type is DNA . poly pdbx seq one letter code can is CGCGAATTCGCG . poly rcsb sample sequence length is 12.0 . mutation is 0.0 . chain is ['A', 'B'] . num chain is 2 . relese date is 1994-12-14 .
 title is SPERM WHALE MYOGLOBIN F46V N-BUTYL ISOCYANIDE AT PH 9.0 . PubMed Abstract is is not available . Experimental Method is X-RAY DIFFRACTION . length a is 91.67 . length b is 91.67 . length c is 45.97 . angle alpha is 90.0 . angle beta is 90.0 . angle gamma is 120.0 . space group name H M is P 6 . ls d res high is 2.07 . ls R factor R work is 0.157 . ls R factor R free is 0.202 . ls R factor obs is 0.157 . Ligand name is ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING FE', 'N-BUTYL ISOCYANIDE'] . lig formula is ['O4 S', 'C34 H32 Fe N4 O4', 'C5 H9 N'] . lig inchi is ['QAOWNCQODCNURD-UHFFFAOYSA-L', 'KABFMIBPWCXCRK-RGGAHWMASA-L', 'FSBLVBBRXSCOKU-UHFFFAOYSA-N'] . UniProt id is P02185 . source organism is Physeter macrocephalus . Molecule is MYOGLOBIN . poly type is polypeptide(L) . poly rcsb entity polymer type is Protein . poly pdbx seq one letter code can is MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRVKHLKTEAEMKASEDLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGNFGADAQGAMNKALELFRKDIAAKYKELGYQG . poly rcsb sample sequence length is 154.0 . mutation is 2.0 . chain is ['A'] . num chain is 1 . relese date is 1997-12-13 .
 title is SEQUENCE-DEPENDENT DRUG BINDING TO THE MINOR GROOVE OF DNA: THE CRYSTAL STRUCTURE OF THE DNA DODECAMER D(CGCAAATTTGCG)2 COMPLEXED WITH PROPAMIDINE . PubMed Abstract is The DNA-binding ligand propamidine, an analogue of the drug pentamidine which is used in the treatment of acquired immune deficiency syndrome (AIDS)-associated Pneumocystis carinii, has been cocrystallized with the DNA sequence d(CGCAAATTTGCG)2, and the crystal structure of the complex has been determined using data from 8 to 2.2 A resolution. The R factor converged to 15.5% with the inclusion of 73 water molecules. The structure shows binding of the propamidine molecule within the AT tract of the DNA minor groove with a shift from the center of the duplex toward the 3' end of ca. 2 A. The long AT tract of six base pairs in length allows the propamidine many potential binding sites in the DNA groove, and its binding is seen to occur where there is least perturbation to the DNA from that seen in the native structure. The interactions with bases are distinct from those previously observed for the sequence d(CGCGAATTCGCG)2. . Experimental Method is X-RAY DIFFRACTION . length a is 24.78 . length b is 41.16 . length c is 65.51 . angle alpha is 90.0 . angle beta is 90.0 . angle gamma is 90.0 . space group name H M is P 21 21 21 . ls d res high is 2.2 . ls R factor R work is 0.155 . ls R factor R free is is not available . ls R factor obs is 0.155 . Ligand name is ['1,3-BIS(AMIDINOPHENOXY)PROPANE'] . lig formula is ['C17 H20 N4 O2'] . lig inchi is ['WTFXJFJYEJZMFO-UHFFFAOYSA-N'] . UniProt id is is not available . source organism is is not available . Molecule is is not available . poly type is polydeoxyribonucleotide . poly rcsb entity polymer type is DNA . poly pdbx seq one letter code can is CGCAAATTTGCG . poly rcsb sample sequence length is 12.0 . mutation is 0.0 . chain is ['A', 'B'] . num chain is 2 . relese date is 1994-12-15 .
 title is HOW AMINO-ACID INSERTIONS ARE ALLOWED IN AN ALPHA-HELIX OF T4 LYSOZYME . PubMed Abstract is Studies of extant protein sequences indicate that amino-acid insertions and deletions are preferentially located in loop regions, which has traditionally been explained as the result of selection removing deleterious mutations within secondary structural elements from the population. But there is no a priori reason to discount the possibility that insertions within secondary structure could either be tolerated until compensatory mutations arise, or have effects that are propagated away from secondary structure into loops. Earlier studies have indicated that insertions are generally tolerated, although much less well within secondary structure elements than in loop regions. Here we show that amino-acid insertions in an alpha-helix of T4 lysozyme can be accepted in two different ways. In some cases the inserted amino acids are accommodated within the helix, leading to the translocation of wild-type residues from the helix to the preceding loop. In other cases the insertion causes a 'looping-out' in the first or last turn of the helix. The individual structural responses seem to be dominated by the maintenance of the interface between the helix and the rest of the protein. . Experimental Method is X-RAY DIFFRACTION . length a is 60.9 . length b is 60.9 . length c is 96.1 . angle alpha is 90.0 . angle beta is 90.0 . angle gamma is 120.0 . space group name H M is P 32 2 1 . ls d res high is 1.74 . ls R factor R work is is not available . ls R factor R free is is not available . ls R factor obs is 0.174 . Ligand name is ['CHLORIDE ION', 'BETA-MERCAPTOETHANOL'] . lig formula is ['Cl', 'C2 H6 O S'] . lig inchi is ['VEXZGXHMUGYJMC-UHFFFAOYSA-M', 'DGVVWUTYPXICAM-UHFFFAOYSA-N'] . UniProt id is P00720 . source organism is Enterobacteria phage T4 . Molecule is T4 LYSOZYME . poly type is polypeptide(L) . poly rcsb entity polymer type is Protein . poly pdbx seq one letter code can is MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYKNL . poly rcsb sample sequence length is 165.0 . mutation is 0.0 . chain is ['A'] . num chain is 1 . relese date is 1992-09-29 .

C:\Users\rkuma\AppData\Local\Temp\ipykernel_12964\3417755023.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  input_data.fillna('is not available', inplace=True)

In [21]:
top_10_data=data_csv.head(10)
compl_data=[]
for i in range(len(top_10_data)):
    data_from_db=''
    for j in range(2,len(names)):
        data_from_db=str(data_from_db)+str(names[j])+' '+str(top_10_data.iloc[i,j])+' .'
    print(data_from_db)

title CRYSTAL STRUCTURE OF THE HIGHLY DISTORTED CHIMERIC DECAMER R(C)D(CGGCGCCG)R(G)-SPERMINE COMPLEX-SPERMINE BINDING TO PHOSPHATE ONLY AND MINOR GROOVE TERTIARY BASE-PAIRING .PubMed Abstract The crystal structure of the self-complementary chimeric decamer duplex r(C)d(CGGCGCCG)r(G), with RNA base pairs at both termini, has been solved at 1.9 A resolution by the molecular replacement method and refined to an R value of 0.145 for 2,314 reflections. The C3'-endo sugar puckers of the terminal riboses apparently drive the entire chimeric duplex into an A-DNA conformation, in contrast to the B-DNA conformation adopted by the all-deoxy decamer of the same sequence. Five symmetry related duplexes encapsulate a spermine molecule which interacts with ten phosphate groups, both directly and through water molecules to form multiple ionic and hydrogen bonding interactions. The spermine interaction severely bends the duplexes by 31 degrees into the major groove at the fourth base pair G(4).C(17), jolts it and slides the 'base plate' into the minor groove. This base pair, together with the adjacent base pair in the top half and the corresponding pseudo two-fold related base pairs in the bottom half, form four minor groove base-paired multiples with the terminal base pairs of two neighboring duplexes. .Experimental Method X-RAY DIFFRACTION .length a 23.98 .length b 40.77 .length c 44.84 .angle alpha 90.0 .angle beta 90.0 .angle gamma 90.0 .space group name H M P 21 21 21 .ls d res high 1.9 .ls R factor R work 0.145 .ls R factor R free is not available .ls R factor obs 0.145 .Ligand name ['SPERMINE'] .lig formula ['C10 H26 N4'] .lig inchi ['PFNFFQXMRSDOHW-UHFFFAOYSA-N'] .UniProt id is not available .source organism is not available .Molecule is not available .poly type polydeoxyribonucleotide/polyribonucleotide hybrid .poly rcsb entity polymer type NA-hybrid .poly pdbx seq one letter code can CCGGCGCCGG .poly rcsb sample sequence length 10.0 .mutation 0.0 .chain ['A', 'B'] .num chain 2 .relese date 1994-12-05 .
title REFINEMENT OF NETROPSIN BOUND TO DNA: BIAS AND FEEDBACK IN ELECTRON DENSITY MAP INTERPRETATION .PubMed Abstract The X-ray crystal structure of the complex of the B-DNA dodecamer CGCGAATTCGCG with the antitumor drug netropsin has been reexamined to locate the drug accurately for computer-based drug design. The optimum solution is with the drug centered in the AATT region of the minor groove, making three good bifurcated hydrogen bonds with adenine N3 and thymine O2 atoms along the floor of the groove. Pyrrole rings of netropsin are packed against the C2 positions of adenines, leaving no room for the amine group of guanine and, hence, providing a structural rationale for the A.T specificity of netropsin. An alternative positioning in which the drug is shifted along the minor groove by ca. one-half base pair step is rejected on the basis of free R factor calculations and the appearance of the original drug-free difference maps. Final omit maps, although of more pleasing appearance, are not a dependable means of discriminating between right and wrong structures. The shifted alternative drug position ignores potential hydrogen bonding along the floor of the groove, provides no explanation for netropsin's observed A.T specificity, and is contradicted by NMR results [Patel, D. J. (1982) Proc. Natl. Acad. Sci. U.S.A. 79, 6424]. .Experimental Method X-RAY DIFFRACTION .length a 24.27 .length b 39.62 .length c 63.57 .angle alpha 90.0 .angle beta 90.0 .angle gamma 90.0 .space group name H M P 21 21 21 .ls d res high 2.25 .ls R factor R work is not available .ls R factor R free 0.252 .ls R factor obs 0.163 .Ligand name ['MAGNESIUM ION', 'NETROPSIN'] .lig formula ['Mg', 'C18 H26 N10 O3'] .lig inchi ['JLVVSXFLKOJNIY-UHFFFAOYSA-N', 'IDBIFFKSXLYUOT-UHFFFAOYSA-N'] .UniProt id is not available .source organism is not available .Molecule is not available .poly type polydeoxyribonucleotide .poly rcsb entity polymer type DNA .poly pdbx seq one letter code can CGCGAATTCGCG .poly rcsb sample sequence length 12.0 .mutation 0.0 .chain ['A', 'B'] .num chain 2 .relese date 1994-12-14 .
title SPERM WHALE MYOGLOBIN F46V N-BUTYL ISOCYANIDE AT PH 9.0 .PubMed Abstract is not available .Experimental Method X-RAY DIFFRACTION .length a 91.67 .length b 91.67 .length c 45.97 .angle alpha 90.0 .angle beta 90.0 .angle gamma 120.0 .space group name H M P 6 .ls d res high 2.07 .ls R factor R work 0.157 .ls R factor R free 0.202 .ls R factor obs 0.157 .Ligand name ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING FE', 'N-BUTYL ISOCYANIDE'] .lig formula ['O4 S', 'C34 H32 Fe N4 O4', 'C5 H9 N'] .lig inchi ['QAOWNCQODCNURD-UHFFFAOYSA-L', 'KABFMIBPWCXCRK-RGGAHWMASA-L', 'FSBLVBBRXSCOKU-UHFFFAOYSA-N'] .UniProt id P02185 .source organism Physeter macrocephalus .Molecule MYOGLOBIN .poly type polypeptide(L) .poly rcsb entity polymer type Protein .poly pdbx seq one letter code can MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRVKHLKTEAEMKASEDLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGNFGADAQGAMNKALELFRKDIAAKYKELGYQG .poly rcsb sample sequence length 154.0 .mutation 2.0 .chain ['A'] .num chain 1 .relese date 1997-12-13 .
title SEQUENCE-DEPENDENT DRUG BINDING TO THE MINOR GROOVE OF DNA: THE CRYSTAL STRUCTURE OF THE DNA DODECAMER D(CGCAAATTTGCG)2 COMPLEXED WITH PROPAMIDINE .PubMed Abstract The DNA-binding ligand propamidine, an analogue of the drug pentamidine which is used in the treatment of acquired immune deficiency syndrome (AIDS)-associated Pneumocystis carinii, has been cocrystallized with the DNA sequence d(CGCAAATTTGCG)2, and the crystal structure of the complex has been determined using data from 8 to 2.2 A resolution. The R factor converged to 15.5% with the inclusion of 73 water molecules. The structure shows binding of the propamidine molecule within the AT tract of the DNA minor groove with a shift from the center of the duplex toward the 3' end of ca. 2 A. The long AT tract of six base pairs in length allows the propamidine many potential binding sites in the DNA groove, and its binding is seen to occur where there is least perturbation to the DNA from that seen in the native structure. The interactions with bases are distinct from those previously observed for the sequence d(CGCGAATTCGCG)2. .Experimental Method X-RAY DIFFRACTION .length a 24.78 .length b 41.16 .length c 65.51 .angle alpha 90.0 .angle beta 90.0 .angle gamma 90.0 .space group name H M P 21 21 21 .ls d res high 2.2 .ls R factor R work 0.155 .ls R factor R free is not available .ls R factor obs 0.155 .Ligand name ['1,3-BIS(AMIDINOPHENOXY)PROPANE'] .lig formula ['C17 H20 N4 O2'] .lig inchi ['WTFXJFJYEJZMFO-UHFFFAOYSA-N'] .UniProt id is not available .source organism is not available .Molecule is not available .poly type polydeoxyribonucleotide .poly rcsb entity polymer type DNA .poly pdbx seq one letter code can CGCAAATTTGCG .poly rcsb sample sequence length 12.0 .mutation 0.0 .chain ['A', 'B'] .num chain 2 .relese date 1994-12-15 .
title HOW AMINO-ACID INSERTIONS ARE ALLOWED IN AN ALPHA-HELIX OF T4 LYSOZYME .PubMed Abstract Studies of extant protein sequences indicate that amino-acid insertions and deletions are preferentially located in loop regions, which has traditionally been explained as the result of selection removing deleterious mutations within secondary structural elements from the population. But there is no a priori reason to discount the possibility that insertions within secondary structure could either be tolerated until compensatory mutations arise, or have effects that are propagated away from secondary structure into loops. Earlier studies have indicated that insertions are generally tolerated, although much less well within secondary structure elements than in loop regions. Here we show that amino-acid insertions in an alpha-helix of T4 lysozyme can be accepted in two different ways. In some cases the inserted amino acids are accommodated within the helix, leading to the translocation of wild-type residues from the helix to the preceding loop. In other cases the insertion causes a 'looping-out' in the first or last turn of the helix. The individual structural responses seem to be dominated by the maintenance of the interface between the helix and the rest of the protein. .Experimental Method X-RAY DIFFRACTION .length a 60.9 .length b 60.9 .length c 96.1 .angle alpha 90.0 .angle beta 90.0 .angle gamma 120.0 .space group name H M P 32 2 1 .ls d res high 1.74 .ls R factor R work is not available .ls R factor R free is not available .ls R factor obs 0.174 .Ligand name ['CHLORIDE ION', 'BETA-MERCAPTOETHANOL'] .lig formula ['Cl', 'C2 H6 O S'] .lig inchi ['VEXZGXHMUGYJMC-UHFFFAOYSA-M', 'DGVVWUTYPXICAM-UHFFFAOYSA-N'] .UniProt id P00720 .source organism Enterobacteria phage T4 .Molecule T4 LYSOZYME .poly type polypeptide(L) .poly rcsb entity polymer type Protein .poly pdbx seq one letter code can MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYKNL .poly rcsb sample sequence length 165.0 .mutation 0.0 .chain ['A'] .num chain 1 .relese date 1992-09-29 .
title SPERM WHALE MYOGLOBIN H64A AQUOMET AT PH 9.0 .PubMed Abstract is not available .Experimental Method X-RAY DIFFRACTION .length a 91.433 .length b 91.433 .length c 45.949 .angle alpha 90.0 .angle beta 90.0 .angle gamma 120.0 .space group name H M P 6 .ls d res high 1.84 .ls R factor R work 0.159 .ls R factor R free 0.203 .ls R factor obs 0.159 .Ligand name ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING FE'] .lig formula ['O4 S', 'C34 H32 Fe N4 O4'] .lig inchi ['QAOWNCQODCNURD-UHFFFAOYSA-L', 'KABFMIBPWCXCRK-RGGAHWMASA-L'] .UniProt id P02185 .source organism Physeter macrocephalus .Molecule MYOGLOBIN .poly type polypeptide(L) .poly rcsb entity polymer type Protein .poly pdbx seq one letter code can MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRFKHLKTEAEMKASEDLKKAGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGNFGADAQGAMNKALELFRKDIAAKYKELGYQG .poly rcsb sample sequence length 154.0 .mutation 2.0 .chain ['A'] .num chain 1 .relese date 1997-12-15 .
title THE UNUSUAL STRUCTURE OF THE HUMAN CENTROMERE (GGA)2 MOTIF: UNPAIRED GUANOSINE RESIDUES STACKED BETWEEN SHEARED G(DOT)A PAIRS .PubMed Abstract The centromere of human chromosomes contains multiple repeats of the DNA sequence d(TGGAA)n. This sequence has the interesting property of pairing with itself to form stable duplexes. We have determined the solution structure of the unusual DNA duplex 5'-TGGAATGGAA:TGGAATGGAA-3' at atomic resolution. The duplex contains unpaired staggered guanosine residues, which co-stack by intercalation between sheared G.A and A.G base-pairs to form an interesting new structural motif, the GA-bracketed G-stack. The TGGAA repeat unit contains six "steps", four of which are not Watson-Crick base-pairs. .Experimental Method SOLUTION NMR .length a is not available .length b is not available .length c is not available .angle alpha is not available .angle beta is not available .angle gamma is not available .space group name H M is not available .ls d res high is not available .ls R factor R work is not available .ls R factor R free is not available .ls R factor obs is not available .Ligand name is not available .lig formula is not available .lig inchi is not available .UniProt id is not available .source organism is not available .Molecule is not available .poly type polydeoxyribonucleotide .poly rcsb entity polymer type DNA .poly pdbx seq one letter code can GTGGAATGGAAC .poly rcsb sample sequence length 12.0 .mutation 0.0 .chain ['A', 'B'] .num chain 2 .relese date 1994-12-16 .
title HOW AMINO-ACID INSERTIONS ARE ALLOWED IN AN ALPHA-HELIX OF T4 LYSOZYME .PubMed Abstract Studies of extant protein sequences indicate that amino-acid insertions and deletions are preferentially located in loop regions, which has traditionally been explained as the result of selection removing deleterious mutations within secondary structural elements from the population. But there is no a priori reason to discount the possibility that insertions within secondary structure could either be tolerated until compensatory mutations arise, or have effects that are propagated away from secondary structure into loops. Earlier studies have indicated that insertions are generally tolerated, although much less well within secondary structure elements than in loop regions. Here we show that amino-acid insertions in an alpha-helix of T4 lysozyme can be accepted in two different ways. In some cases the inserted amino acids are accommodated within the helix, leading to the translocation of wild-type residues from the helix to the preceding loop. In other cases the insertion causes a 'looping-out' in the first or last turn of the helix. The individual structural responses seem to be dominated by the maintenance of the interface between the helix and the rest of the protein. .Experimental Method X-RAY DIFFRACTION .length a 60.9 .length b 60.9 .length c 95.6 .angle alpha 90.0 .angle beta 90.0 .angle gamma 120.0 .space group name H M P 32 2 1 .ls d res high 1.9 .ls R factor R work is not available .ls R factor R free is not available .ls R factor obs 0.182 .Ligand name ['CHLORIDE ION', 'BETA-MERCAPTOETHANOL'] .lig formula ['Cl', 'C2 H6 O S'] .lig inchi ['VEXZGXHMUGYJMC-UHFFFAOYSA-M', 'DGVVWUTYPXICAM-UHFFFAOYSA-N'] .UniProt id P00720 .source organism Enterobacteria phage T4 .Molecule T4 LYSOZYME .poly type polypeptide(L) .poly rcsb entity polymer type Protein .poly pdbx seq one letter code can MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNSLDAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYKNL .poly rcsb sample sequence length 167.0 .mutation 0.0 .chain ['A'] .num chain 1 .relese date 1992-09-29 .
title SPERM WHALE MYOGLOBIN H64A N-BUTYL ISOCYANIDE AT PH 9.0 .PubMed Abstract is not available .Experimental Method X-RAY DIFFRACTION .length a 91.63 .length b 91.63 .length c 46.014 .angle alpha 90.0 .angle beta 90.0 .angle gamma 120.0 .space group name H M P 6 .ls d res high 2.07 .ls R factor R work 0.158 .ls R factor R free 0.216 .ls R factor obs 0.158 .Ligand name ['N-BUTYL ISOCYANIDE', 'SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING FE'] .lig formula ['C5 H9 N', 'O4 S', 'C34 H32 Fe N4 O4'] .lig inchi ['FSBLVBBRXSCOKU-UHFFFAOYSA-N', 'QAOWNCQODCNURD-UHFFFAOYSA-L', 'KABFMIBPWCXCRK-RGGAHWMASA-L'] .UniProt id P02185 .source organism Physeter macrocephalus .Molecule MYOGLOBIN .poly type polypeptide(L) .poly rcsb entity polymer type Protein .poly pdbx seq one letter code can MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRFKHLKTEAEMKASEDLKKAGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGNFGADAQGAMNKALELFRKDIAAKYKELGYQG .poly rcsb sample sequence length 154.0 .mutation 2.0 .chain ['A'] .num chain 1 .relese date 1997-12-16 .
title DNA DUPLEXES FLANKED BY HYBRID DUPLEXES: THE SOLUTION STRUCTURE OF CHIMERIC JUNCTIONS IN .PubMed Abstract Hybrid duplexes and chimeric duplexes containing hybrid segments linked to pure DNA (or pure RNA) segments are involved in transcription and replication, as well as reverse transcription. A complete understanding of the mechanism of these processes requires detailed information on such duplexes and the junctions between duplexes of differing structure. Using two-dimensional NMR, restrained molecular dynamics and mechanics, and back-calculation refinement against the nuclear Overhauser effect spectra at various mixing times, we have determined the solution structure of the chimeric duplex [r(cgcg)d-(TATACGCG)]2 containing a pure DNA segment in the center of a hybrid duplex. The solution structure differs from the previously determined X-ray structure of the analogous duplex [r(gcg)d(TATACGC)]2, which was found to be A-form throughout [Wang, A.H.-J., et al. (1982) Nature 299, 601-604]. The basic features of the solution structure are (a) the RNA residues are all A-form with C3'-endo sugar conformations, (b) the central DNA segment is B-form, (c) the transition from A-form RNA sugar conformations to B-form DNA sugar conformations involves only the dT5 base step, and (d) although the sugar conformations of the DNA residues A6-G12 are closer to B-form, the basic helical properties of the peripheral RNA.DNA hybrid segments are closer to typical A-form than to B-form. .Experimental Method SOLUTION NMR .length a is not available .length b is not available .length c is not available .angle alpha is not available .angle beta is not available .angle gamma is not available .space group name H M is not available .ls d res high is not available .ls R factor R work is not available .ls R factor R free is not available .ls R factor obs is not available .Ligand name is not available .lig formula is not available .lig inchi is not available .UniProt id is not available .source organism is not available .Molecule is not available .poly type polydeoxyribonucleotide/polyribonucleotide hybrid .poly rcsb entity polymer type NA-hybrid .poly pdbx seq one letter code can CGCGTATACGCG .poly rcsb sample sequence length 12.0 .mutation 0.0 .chain ['A', 'B'] .num chain 2 .relese date 1994-12-16 .

In [23]:
test_data='Protein_data/1_50k_pdb.csv'
dd=pd.read_csv(test_data)
dd

,rcsb_id,pubmed_id,title,PubMed Abstract,Experimental Method,length_a,length_b,length_c,angle_alpha,angle_beta,...,source_organism,Molecule,poly_type,poly_rcsb_entity_polymer_type,poly_pdbx_seq_one_letter_code_can,poly_rcsb_sample_sequence_length,mutation,chain,num_chain,relese_date
0,100D,7816639.0,CRYSTAL STRUCTURE OF THE HIGHLY DISTORTED CHIM...,The crystal structure of the self-complementar...,X-RAY DIFFRACTION,23.980,40.770,44.840,90.0,90.00,...,NaN,NaN,polydeoxyribonucleotide/polyribonucleotide hybrid,NA-hybrid,CCGGCGCCGG,10.0,0.0,"['A', 'B']",2,1994-12-05
1,101D,7711020.0,REFINEMENT OF NETROPSIN BOUND TO DNA: BIAS AND...,The X-ray crystal structure of the complex of ...,X-RAY DIFFRACTION,24.270,39.620,63.570,90.0,90.00,...,NaN,NaN,polydeoxyribonucleotide,DNA,CGCGAATTCGCG,12.0,0.0,"['A', 'B']",2,1994-12-14
2,101M,NaN,SPERM WHALE MYOGLOBIN F46V N-BUTYL ISOCYANIDE ...,NaN,X-RAY DIFFRACTION,91.670,91.670,45.970,90.0,90.00,...,Physeter macrocephalus,MYOGLOBIN,polypeptide(L),Protein,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...,154.0,2.0,['A'],1,1997-12-13
3,102D,7608897.0,SEQUENCE-DEPENDENT DRUG BINDING TO THE MINOR G...,"The DNA-binding ligand propamidine, an analogu...",X-RAY DIFFRACTION,24.780,41.160,65.510,90.0,90.00,...,NaN,NaN,polydeoxyribonucleotide,DNA,CGCAAATTTGCG,12.0,0.0,"['A', 'B']",2,1994-12-15
4,102L,8429913.0,HOW AMINO-ACID INSERTIONS ARE ALLOWED IN AN AL...,Studies of extant protein sequences indicate t...,X-RAY DIFFRACTION,60.900,60.900,96.100,90.0,90.00,...,Enterobacteria phage T4,T4 LYSOZYME,polypeptide(L),Protein,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSE...,165.0,0.0,['A'],1,1992-09-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2R5D,17942675.0,Structure of the gp41 N-trimer in complex with...,"During HIV-1 entry, the highly conserved gp41 ...",X-RAY DIFFRACTION,35.438,56.345,53.424,90.0,96.90,...,NaN,NaN,polypeptide(L),Protein,XRMKQIEDKIEEIESKQKKIENEIARIKKLLQLTVWGIKQLQARILX,47.0,0.0,"['A', 'B', 'C']",3,2007-09-03
49996,2R5E,18186649.0,Aedes kynurenine aminotransferase in complex w...,Aedes aegypti kynurenine aminotransferase (AeK...,X-RAY DIFFRACTION,56.374,95.589,165.901,90.0,90.00,...,Aedes aegypti,Kynurenine aminotransferase,polypeptide(L),Protein,MSSTSNETMHNKFDLPKRYQGSTKSVWVEYIQLAAQYKPLNLGQGF...,429.0,0.0,"['A', 'B']",2,2007-09-03
49997,2R5F,NaN,Putative sugar-binding domain of transcription...,NaN,X-RAY DIFFRACTION,42.112,42.112,144.782,90.0,90.00,...,Pseudomonas syringae pv. tomato (strain ATCC B...,"Transcriptional regulator, putative",polypeptide(L),Protein,SNARPQGLHLELETRLQKMYGIRQVIVVEATEPDDEESIKQAIGSA...,264.0,0.0,['A'],1,2007-09-03
49998,2R5G,17945253.0,"Structure of human CLIC2, crystal form B",Chloride intracellular channel (CLIC) proteins...,X-RAY DIFFRACTION,35.973,66.940,44.071,90.0,99.86,...,Homo sapiens,Chloride intracellular channel protein 2,polypeptide(L),Protein,MSGLRPGTQVDPEIELFVKAGSDGESIGNCPFCQRLFMILWLKGVK...,247.0,0.0,['A'],1,2007-09-03
49999,2R5H,17804402.0,Pentamer structure of Major Capsid Protein L1 ...,Human papillomaviruses (HPVs) are known etiolo...,X-RAY DIFFRACTION,105.000,159.052,413.738,90.0,90.00,...,Human papillomavirus,Late major capsid protein L1,polypeptide(L),Protein,AVVSTDEYVARTNIYYHAGTSRLLAVGHPYFPIKKPNNNKILVPKV...,424.0,2.0,"['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', ...",15,2007-09-03

In [39]:
list_csv[0]

{'rcsb_id': '100D',
 'pubmed_id': 7816639.0,
 'title': 'CRYSTAL STRUCTURE OF THE HIGHLY DISTORTED CHIMERIC DECAMER R(C)D(CGGCGCCG)R(G)-SPERMINE COMPLEX-SPERMINE BINDING TO PHOSPHATE ONLY AND MINOR GROOVE TERTIARY BASE-PAIRING',
 'PubMed Abstract': "The crystal structure of the self-complementary chimeric decamer duplex r(C)d(CGGCGCCG)r(G), with RNA base pairs at both termini, has been solved at 1.9 A resolution by the molecular replacement method and refined to an R value of 0.145 for 2,314 reflections. The C3'-endo sugar puckers of the terminal riboses apparently drive the entire chimeric duplex into an A-DNA conformation, in contrast to the B-DNA conformation adopted by the all-deoxy decamer of the same sequence. Five symmetry related duplexes encapsulate a spermine molecule which interacts with ten phosphate groups, both directly and through water molecules to form multiple ionic and hydrogen bonding interactions. The spermine interaction severely bends the duplexes by 31 degrees into the major groove at the fourth base pair G(4).C(17), jolts it and slides the 'base plate' into the minor groove. This base pair, together with the adjacent base pair in the top half and the corresponding pseudo two-fold related base pairs in the bottom half, form four minor groove base-paired multiples with the terminal base pairs of two neighboring duplexes.",
 'Experimental Method': 'X-RAY DIFFRACTION',
 'length_a': 23.98,
 'length_b': 40.77,
 'length_c': 44.84,
 'angle_alpha': 90.0,
 'angle_beta': 90.0,
 'angle_gamma': 90.0,
 'space_group_name_H_M': 'P 21 21 21',
 'ls_d_res_high': 1.9,
 'ls_R_factor_R_work': 0.145,
 'ls_R_factor_R_free': nan,
 'ls_R_factor_obs': 0.145,
 'Ligand_name': "['SPERMINE']",
 'lig_formula': "['C10 H26 N4']",
 'lig_inchi': "['PFNFFQXMRSDOHW-UHFFFAOYSA-N']",
 'UniProt_id': nan,
 'source_organism': nan,
 'Molecule': nan,
 'poly_type': 'polydeoxyribonucleotide/polyribonucleotide hybrid',
 'poly_rcsb_entity_polymer_type': 'NA-hybrid',
 'poly_pdbx_seq_one_letter_code_can': 'CCGGCGCCGG',
 'poly_rcsb_sample_sequence_length': 10.0,
 'mutation': 0.0,
 'chain': "['A', 'B']",
 'num_chain': 2,
 'relese_date': '1994-12-05'}

In [18]:

if not os.path.exists(DB_LOCATION):
    print(f"Chroma database not found at '{DB_LOCATION}'. Creating a new one...")
    documents = []
    for i, row in df.iterrows():
        if 'Review' not in row or pd.isna(row['Review']):
            print(f"Skipping row {i} due to missing or empty 'Review'.")
            continue
        doc = Document(
            page_content=row['Review'],
            metadata=list_csv[i],
            id=str(i)
        )
        documents.append(doc)

    if documents:
        db = Chroma.from_documents(
            documents=documents,
            embedding=embeddings,
            persist_directory=DB_LOCATION
        )
        db.persist()
        print(f"Successfully added {len(documents)} documents and persisted Chroma DB.")
    else:
        print("No valid documents found to add to the database. Exiting.")
        exit()
else:
    print(f"Chroma database found at '{DB_LOCATION}'. Loading existing database...")
    db = Chroma(persist_directory=DB_LOCATION, embedding_function=embeddings)
    print("Chroma database loaded successfully.")

# --- 4. Obtain the Retriever ---
if db:
    retriever = db.as_retriever(search_kwargs={'k':3})
    print("Retriever successfully created from the Chroma database!")
else:
    print("Could not create or load the Chroma database. Retriever not available.")
    exit() # Exit if retriever can't be obtained

"I'm just a computer program, so I don't have feelings or emotions like humans do. I'm functioning properly and ready to help with any questions or tasks you may have! How about you? Is there something on your mind that you'd like to chat about or ask for help with?"

In [27]:
import json

In [28]:
resp=str(resp)
json_string_data = resp.replace("'", '"')
json_string_data = json_string_data.replace(": None", ": null")
json_string_data 
data_from_string = json.loads(json_string_data)
data_from_string

JSONDecodeError: Expecting ',' delimiter: line 1 column 1507 (char 1506)

In [ ]:

if not os.path.exists(DB_LOCATION):
    print(f"Chroma database not found at '{DB_LOCATION}'. Creating a new one...")
    documents = []
    for i, row in df.iterrows():
        if 'Review' not in row or pd.isna(row['Review']):
            print(f"Skipping row {i} due to missing or empty 'Review'.")
            continue
        doc = Document(
            page_content=row['Review'],
            metadata=list_csv[i],
            id=str(i)
        )
        documents.append(doc)

    if documents:
        db = Chroma.from_documents(
            documents=documents,
            embedding=embeddings,
            persist_directory=DB_LOCATION
        )
        db.persist()
        print(f"Successfully added {len(documents)} documents and persisted Chroma DB.")
    else:
        print("No valid documents found to add to the database. Exiting.")
        exit()
else:
    print(f"Chroma database found at '{DB_LOCATION}'. Loading existing database...")
    db = Chroma(persist_directory=DB_LOCATION, embedding_function=embeddings)
    print("Chroma database loaded successfully.")

# --- 4. Obtain the Retriever ---
if db:
    retriever = db.as_retriever(search_kwargs={'k':3})
    print("Retriever successfully created from the Chroma database!")
else:
    print("Could not create or load the Chroma database. Retriever not available.")
    exit() # Exit if retriever can't be obtained

In [6]:

# CSV_FILE = '2k_pdb.csv'
# DB_LOCATION = "./pdb_langchain_db" 
# OLLAMA_EMBEDDING_MODEL = 'mxbai-embed-large'
# OLLAMA_LLM_MODEL = 'qwen2.5:7b'


# try:
#     input_data=pd.read_csv(CSV_FILE).head(50)
#     input_data.fillna('is not available', inplace=True)
#     names=[]
#     for i in input_data.columns:
#         j=i.replace('_',' ')
#         names.append(j)
#     compl_data=[]
#     documents=[]
#     for i in range(len(input_data)):
#         data_from_db=''
#         for j in range(2,len(names)):
#             data_from_db=f'{str(data_from_db)} {str(names[j])} is {str(input_data.iloc[i,j])} .'
#         doc = Document(
#                 page_content=data_from_db,
#                 metadata={
#                     'rcsb id': input_data.iloc[i,0],
#                     'Pubmed id':input_data.iloc[i,1]
#                 }
#             )
#         documents.append(doc)
#     print(f"Prepared {len(documents)} documents for embedding.")


# except FileNotFoundError:
#     print(f"Error: '{CSV_FILE}' not found. Please ensure the PDF file is in the correct directory.")
#     exit()
# except Exception as e:
#     print(f"Error loading PDF: {e}")
#     exit()


# try:
#     embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)
# except Exception as e:
#     print(f"Error initializing Ollama Embeddings: {e}")
#     print(f"Please ensure Ollama is running and the model '{OLLAMA_EMBEDDING_MODEL}' is pulled (ollama pull {OLLAMA_EMBEDDING_MODEL}).")
#     exit()

# # --- 3. Prepare or Load Chroma Database (Adjusted for PDF documents list) ---
# db = None
# if not os.path.exists(DB_LOCATION):
#     print(f"Chroma database not found at '{DB_LOCATION}'. Creating a new one...")
#     # 'documents' is already prepared from the PDF loader
#     if documents:
#         db = Chroma.from_documents(
#             documents=documents, # Use the 'documents' list from PDF loading
#             embedding=embeddings,
#             persist_directory=DB_LOCATION
#         )
#         # db.persist()
#         print(f"Successfully added {len(documents)} documents (from PDF) and persisted Chroma DB.")
#     else:
#         print("No valid documents found from PDF to add to the database. Exiting.")
#         exit()
# else:
#     print(f"Chroma database found at '{DB_LOCATION}'. Loading existing database.")
#     db = Chroma(persist_directory=DB_LOCATION, embedding_function=embeddings)
#     print("Chroma database loaded successfully.")

# # --- 4. Obtain the Retriever (Same as before) ---
# if db:
#     retriever = db.as_retriever()
#     print("Retriever successfully created from the Chroma database!")
# else:
#     print("Could not create or load the Chroma database. Retriever not available.")
#     exit()

# # --- 5. Initialize the Language Model (LLM) (Same as before) ---
# print(f"Initializing Ollama LLM with model: {OLLAMA_LLM_MODEL}...")
# try:
#     model = Ollama(model=OLLAMA_LLM_MODEL)
#     print("Ollama LLM initialized successfully.")
# except Exception as e:
#     print(f"Error initializing Ollama LLM: {e}")
#     print(f"Please ensure Ollama is running and the model '{OLLAMA_LLM_MODEL}' is pulled (ollama pull {OLLAMA_LLM_MODEL}).")
#     exit()

Prepared 50 documents for embedding.
Chroma database found at './pdb_langchain_db'. Loading existing database.
Chroma database loaded successfully.
Retriever successfully created from the Chroma database!
Initializing Ollama LLM with model: qwen2.5:7b...
Ollama LLM initialized successfully.

C:\Users\rkuma\AppData\Local\Temp\ipykernel_5428\3322410439.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'is not available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_data.fillna('is not available', inplace=True)

In [6]:
import pandas as pd
import os
from langchain_community.embeddings import OllamaEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_community.llms import Ollama
from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate # Added this import, assuming it's used later in the full script
from langchain_ollama import OllamaLLM

CSV_FILE = '2k_pdb.csv'
DB_LOCATION = "./pdb_langchain_db"
OLLAMA_EMBEDDING_MODEL = 'mxbai-embed-large'
OLLAMA_LLM_MODEL = 'qwen2.5:7b'


try:
    # --- CHANGE MADE HERE: Removed .head(50) ---
    input_data = pd.read_csv(CSV_FILE).head(100)
    input_data.fillna('is not available', inplace=True)
    names = []
    for i in input_data.columns:
        j = i.replace('_',' ')
        names.append(j)
    compl_data = [] # This variable is declared but not used. You might want to remove it if it's not needed.
    documents = []
    for i in range(len(input_data)):
        data_from_db = ''
        for j in range(2,len(names)):
            data_from_db = f'{str(data_from_db)} {str(names[j])} is {str(input_data.iloc[i,j])} .'
        print('i',i)
        doc = Document(
                page_content=data_from_db,
                metadata={
                    'rcsb id': input_data.iloc[i,0],
                    'Pubmed id':input_data.iloc[i,1]
                }
                # It's generally good practice to include an 'id' for documents if you need to reference them later
                # id=str(i) # You had this in a previous version, consider adding it back if beneficial
            )
        documents.append(doc)
    print(f"Prepared {len(documents)} documents for embedding.")


except FileNotFoundError:
    print(f"Error: '{CSV_FILE}' not found. Please ensure the CSV file is in the correct directory.")
    exit()
except Exception as e:
    print(f"Error loading CSV: {e}") # Changed from PDF to CSV
    exit()


try:
    embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)
except Exception as e:
    print(f"Error initializing Ollama Embeddings: {e}")
    print(f"Please ensure Ollama is running and the model '{OLLAMA_EMBEDDING_MODEL}' is pulled (ollama pull {OLLAMA_EMBEDDING_MODEL}).")
    exit()

# --- 3. Prepare or Load Chroma Database ---
db = None
if not os.path.exists(DB_LOCATION):
    print(f"Chroma database not found at '{DB_LOCATION}'. Creating a new one...")
    if documents:
        db = Chroma.from_documents(
            documents=documents, # Use the 'documents' list
            embedding=embeddings,
            persist_directory=DB_LOCATION
        )
        # db.persist() # Chroma.from_documents with persist_directory usually handles persistence automatically on creation
        print(f"Successfully added {len(documents)} documents (from CSV) and persisted Chroma DB.") # Changed from PDF to CSV
    else:
        print("No valid documents found from CSV to add to the database. Exiting.") # Changed from PDF to CSV
        exit()
else:
    print(f"Chroma database found at '{DB_LOCATION}'. Loading existing database.")
    db = Chroma(persist_directory=DB_LOCATION, embedding_function=embeddings)
    print("Chroma database loaded successfully.")

# --- 4. Obtain the Retriever ---
if db:
    retriever = db.as_retriever()
    print("Retriever successfully created from the Chroma database!")
else:
    print("Could not create or load the Chroma database. Retriever not available.")
    exit()

# --- 5. Initialize the Language Model (LLM) ---
print(f"Initializing Ollama LLM with model: {OLLAMA_LLM_MODEL}...")
try:
    model = OllamaLLM(model=OLLAMA_LLM_MODEL) #Ollama
    print("Ollama LLM initialized successfully.")
except Exception as e:
    print(f"Error initializing Ollama LLM: {e}")
    print(f"Please ensure Ollama is running and the model '{OLLAMA_LLM_MODEL}' is pulled (ollama pull {OLLAMA_LLM_MODEL}).")
    exit()

C:\Users\rkuma\AppData\Local\Temp\ipykernel_10512\2709752268.py:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'is not available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_data.fillna('is not available', inplace=True)
C:\Users\rkuma\AppData\Local\Temp\ipykernel_10512\2709752268.py:53: LangChainDeprecationWarning: The class `OllamaEmbeddings` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the :class:`~langchain-ollama package and should be used instead. To use it run `pip install -U :class:`~langchain-ollama` and import as `from :class:`~langchain_ollama import OllamaEmbeddings``.
  embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)
C:\Users\rkuma\AppData\Local\Temp\ipykernel_10512\2709752268.py:76: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-chroma package and should be used instead. To use it run `pip install -U :class:`~langchain-chroma` and import as `from :class:`~langchain_chroma import Chroma``.
  db = Chroma(persist_directory=DB_LOCATION, embedding_function=embeddings)

i 0
i 1
i 2
i 3
i 4
i 5
i 6
i 7
i 8
i 9
i 10
i 11
i 12
i 13
i 14
i 15
i 16
i 17
i 18
i 19
i 20
i 21
i 22
i 23
i 24
i 25
i 26
i 27
i 28
i 29
i 30
i 31
i 32
i 33
i 34
i 35
i 36
i 37
i 38
i 39
i 40
i 41
i 42
i 43
i 44
i 45
i 46
i 47
i 48
i 49
i 50
i 51
i 52
i 53
i 54
i 55
i 56
i 57
i 58
i 59
i 60
i 61
i 62
i 63
i 64
i 65
i 66
i 67
i 68
i 69
i 70
i 71
i 72
i 73
i 74
i 75
i 76
i 77
i 78
i 79
i 80
i 81
i 82
i 83
i 84
i 85
i 86
i 87
i 88
i 89
i 90
i 91
i 92
i 93
i 94
i 95
i 96
i 97
i 98
i 99
Prepared 100 documents for embedding.
Chroma database found at './pdb_langchain_db'. Loading existing database.
Chroma database loaded successfully.
Could not create or load the Chroma database. Retriever not available.
Initializing Ollama LLM with model: qwen2.5:7b...
Ollama LLM initialized successfully.

In [ ]:

# --- 6. Define the Prompt Template ---
template = """
You are an expert in bioinformatics , bio technology   .

Here are some relevant protein data:
{protein_info}

Here is the question to answer: {question}
"""
prompt = ChatPromptTemplate.from_template(template)

chain = prompt | model

while True:
    question = input('Ask your question: ')
    print(f"Your question: {question}") # Changed to print only the question once

    if question.lower() == 'q':
        print("Exiting Q&A session.")
        break
    else:
        # Step 1: Retrieve relevant documents (reviews)
        # The 'review' variable will actually be a list of Document objects
        retrieved_docs = retriever.invoke(question)

        # Extract just the page_content (the review text) from the Document objects
        # and join them into a single string to pass to the prompt
        formatted_reviews = "\n\n".join([doc.page_content for doc in retrieved_docs])

        # Step 2: Invoke the chain with the retrieved reviews and the user's question
        result = chain.invoke({'reviews': formatted_reviews, 'question': question})

        # Step 3: Print the result from the LLM
        print("\n--- LLM Response ---")
        print(result) # For Ollama, the result is usually a string directly
        print("---------------------\n")

In [ ]:


# --- Configuration (Copied from our previous successful iteration) ---
CSV_FILE = 'Restaurant reviews.csv'
DB_LOCATION = "./chrome_lanfchain_db"
OLLAMA_EMBEDDING_MODEL = 'mxbai-embed-large' # Model for embeddings
OLLAMA_LLM_MODEL = 'llama3.2' # Model for the LLM (e.g., Llama 3, Mistral, etc.) - IMPORTANT!


df = pd.read_csv(CSV_FILE)
embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)

if not os.path.exists(DB_LOCATION):
    print(f"Chroma database not found at '{DB_LOCATION}'. Creating a new one...")
    documents = []
    for i, row in df.iterrows():
        if 'Review' not in row or pd.isna(row['Review']):
            print(f"Skipping row {i} due to missing or empty 'Review'.")
            continue
        doc = Document(
            page_content=row['Review'],
            metadata={
                'rating': row.get('Rating'),
                'date': row.get('Time'),
                'reviewer': row.get('Reviewer')
            },
            id=str(i)
        )
        documents.append(doc)

    if documents:
        db = Chroma.from_documents(
            documents=documents,
            embedding=embeddings,
            persist_directory=DB_LOCATION
        )
        db.persist()
        print(f"Successfully added {len(documents)} documents and persisted Chroma DB.")
    else:
        print("No valid documents found to add to the database. Exiting.")
        exit()
else:
    print(f"Chroma database found at '{DB_LOCATION}'. Loading existing database...")
    db = Chroma(persist_directory=DB_LOCATION, embedding_function=embeddings)
    print("Chroma database loaded successfully.")


if db:
    retriever = db.as_retriever(search_kwargs={'k':3})
    print("Retriever successfully created from the Chroma database!")
else:
    print("Could not create or load the Chroma database. Retriever not available.")
    exit()
    

try:
    model = Ollama(model=OLLAMA_LLM_MODEL)
    print("Ollama LLM initialized successfully.")
except Exception as e:
    print(f"Error initializing Ollama LLM: {e}")
    exit()


template = """
You are an expert in answering questions about a pizza restaurant based on provided reviews.

Here are some relevant reviews:
{reviews}

Here is the question to answer: {question}
"""
prompt = ChatPromptTemplate.from_template(template)
chain = prompt | model


while True:
    question = input('Ask your question: ')
    print(f"Your question: {question}") 

    if question.lower() == 'q':
        print("Exiting Q&A session.")
        break
    else:
        # Step 1: Retrieve relevant documents (reviews)
        # The 'review' variable will actually be a list of Document objects
        retrieved_docs = retriever.invoke(question)

        # Extract just the page_content (the review text) from the Document objects
        # and join them into a single string to pass to the prompt
        formatted_reviews = "\n\n".join([doc.page_content for doc in retrieved_docs])

        # Step 2: Invoke the chain with the retrieved reviews and the user's question
        result = chain.invoke({'reviews': formatted_reviews, 'question': question})

        # Step 3: Print the result from the LLM
        print("\n--- LLM Response ---")
        print(result) # For Ollama, the result is usually a string directly
        print("---------------------\n")

In [1]:
import pandas as pd
import os
from langchain_community.embeddings import OllamaEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_community.llms import Ollama
from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate


CSV_FILE = '2k_pdb.csv'
DB_LOCATION = "./pdb_langchain_db"
OLLAMA_EMBEDDING_MODEL = 'mxbai-embed-large'
OLLAMA_LLM_MODEL = 'qwen2.5:7b'


try:
    input_data = pd.read_csv(CSV_FILE).head(5)
    input_data.fillna('is not available', inplace=True)
    names = []
    for i in input_data.columns:
        j = i.replace('_', ' ')
        names.append(j)
    compl_data = []
    documents = []
    for i in range(len(input_data)):
        data_from_db = ''
        for j in range(2, len(names)):
            data_from_db = f'{str(data_from_db)} {str(names[j])} is {str(input_data.iloc[i,j])} .'

        print('data_from_db',data_from_db)
        doc = Document(
                page_content=data_from_db,
                metadata={
                    'rcsb id': input_data.iloc[i,0],
                    'Pubmed id':input_data.iloc[i,1]
                },
                id=str(i)
            )
        documents.append(doc)
    print(f"Prepared {len(documents)} documents for embedding.")


except FileNotFoundError:
    print(f"Error: '{CSV_FILE}' not found. Please ensure the PDF file is in the correct directory.")
    exit()
except Exception as e:
    print(f"Error loading PDF: {e}")
    exit()


try:
    embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)
except Exception as e:
    print(f"Error initializing Ollama Embeddings: {e}")
    print(f"Please ensure Ollama is running and the model '{OLLAMA_EMBEDDING_MODEL}' is pulled (ollama pull {OLLAMA_EMBEDDING_MODEL}).")
    exit()

# --- 3. Prepare or Load Chroma Database (Adjusted for PDF documents list) ---
db = None
if not os.path.exists(DB_LOCATION):
    print(f"Chroma database not found at '{DB_LOCATION}'. Creating a new one...")
    # 'documents' is already prepared from the PDF loader
    if documents:
        db = Chroma.from_documents(
            documents=documents, # Use the 'documents' list from PDF loading
            embedding=embeddings,
            persist_directory=DB_LOCATION
        )
        # db.persist()
        print(f"Successfully added {len(documents)} documents (from PDF) and persisted Chroma DB.")
    else:
        print("No valid documents found from PDF to add to the database. Exiting.")
        exit()
else:
    print(f"Chroma database found at '{DB_LOCATION}'. Loading existing database.")
    db = Chroma(persist_directory=DB_LOCATION, embedding_function=embeddings)
    print("Chroma database loaded successfully.")

# --- 4. Obtain the Retriever (Same as before) ---
if db:
    retriever = db.as_retriever()
    print("Retriever successfully created from the Chroma database!")
else:
    print("Could not create or load the Chroma database. Retriever not available.")
    exit()

# --- 5. Initialize the Language Model (LLM) (Same as before) ---
print(f"Initializing Ollama LLM with model: {OLLAMA_LLM_MODEL}...")
try:
    model = Ollama(model=OLLAMA_LLM_MODEL)
    print("Ollama LLM initialized successfully.")
except Exception as e:
    print(f"Error initializing Ollama LLM: {e}")
    print(f"Please ensure Ollama is running and the model '{OLLAMA_LLM_MODEL}' is pulled (ollama pull {OLLAMA_LLM_MODEL}).")
    exit()

# ---
# ## Corrected Prompt Template and Chain Invocation

# The key changes are here:

# ```python
# # --- 6. Define the Prompt Template ---
template = """
You are an expert in bioinformatics and biotechnology.

Here is some relevant protein data:
{protein_info}

Here is the question to answer: {question}
"""
prompt = ChatPromptTemplate.from_template(template)

chain = prompt | model

while True:
    question = input('Ask your question: ')
    print(f"Your question: {question}")

    if question.lower() == 'q':
        print("Exiting Q&A session.")
        break
    else:
        # Step 1: Retrieve relevant documents (now representing protein info)
        retrieved_docs = retriever.invoke(question)

        # Extract just the page_content (the protein data text) from the Document objects
        # and join them into a single string to pass to the prompt
        formatted_protein_info = "\n\n".join([doc.page_content for doc in retrieved_docs])

        # Step 2: Invoke the chain with the retrieved protein info and the user's question
        result = chain.invoke({'protein_info': formatted_protein_info, 'question': question})

        # Step 3: Print the result from the LLM
        print("\n--- LLM Response ---")
        print(result)
        print("---------------------\n")

C:\Users\rkuma\AppData\Local\Temp\ipykernel_1880\3558797967.py:18: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'is not available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  input_data.fillna('is not available', inplace=True)
C:\Users\rkuma\AppData\Local\Temp\ipykernel_1880\3558797967.py:52: LangChainDeprecationWarning: The class `OllamaEmbeddings` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the :class:`~langchain-ollama package and should be used instead. To use it run `pip install -U :class:`~langchain-ollama` and import as `from :class:`~langchain_ollama import OllamaEmbeddings``.
  embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)
C:\Users\rkuma\AppData\Local\Temp\ipykernel_1880\3558797967.py:76: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-chroma package and should be used instead. To use it run `pip install -U :class:`~langchain-chroma` and import as `from :class:`~langchain_chroma import Chroma``.
  db = Chroma(persist_directory=DB_LOCATION, embedding_function=embeddings)

data_from_db  title is CRYSTAL STRUCTURE OF THE HIGHLY DISTORTED CHIMERIC DECAMER R(C)D(CGGCGCCG)R(G)-SPERMINE COMPLEX-SPERMINE BINDING TO PHOSPHATE ONLY AND MINOR GROOVE TERTIARY BASE-PAIRING . PubMed Abstract is The crystal structure of the self-complementary chimeric decamer duplex r(C)d(CGGCGCCG)r(G), with RNA base pairs at both termini, has been solved at 1.9 A resolution by the molecular replacement method and refined to an R value of 0.145 for 2,314 reflections. The C3'-endo sugar puckers of the terminal riboses apparently drive the entire chimeric duplex into an A-DNA conformation, in contrast to the B-DNA conformation adopted by the all-deoxy decamer of the same sequence. Five symmetry related duplexes encapsulate a spermine molecule which interacts with ten phosphate groups, both directly and through water molecules to form multiple ionic and hydrogen bonding interactions. The spermine interaction severely bends the duplexes by 31 degrees into the major groove at the fourth base pair G(4).C(17), jolts it and slides the 'base plate' into the minor groove. This base pair, together with the adjacent base pair in the top half and the corresponding pseudo two-fold related base pairs in the bottom half, form four minor groove base-paired multiples with the terminal base pairs of two neighboring duplexes. . Experimental Method is X-RAY DIFFRACTION . length a is 23.98 . length b is 40.77 . length c is 44.84 . angle alpha is 90.0 . angle beta is 90.0 . angle gamma is 90.0 . space group name H M is P 21 21 21 . ls d res high is 1.9 . ls R factor R work is 0.145 . ls R factor R free is is not available . ls R factor obs is 0.145 . Ligand name is ['SPERMINE'] . lig formula is ['C10 H26 N4'] . lig inchi is ['PFNFFQXMRSDOHW-UHFFFAOYSA-N'] . UniProt id is is not available . source organism is is not available . Molecule is is not available . poly type is polydeoxyribonucleotide/polyribonucleotide hybrid . poly rcsb entity polymer type is NA-hybrid . poly pdbx seq one letter code can is CCGGCGCCGG . poly rcsb sample sequence length is 10.0 . mutation is 0.0 . chain is ['A', 'B'] . num chain is 2 . relese date is 1994-12-05 .
data_from_db  title is REFINEMENT OF NETROPSIN BOUND TO DNA: BIAS AND FEEDBACK IN ELECTRON DENSITY MAP INTERPRETATION . PubMed Abstract is The X-ray crystal structure of the complex of the B-DNA dodecamer CGCGAATTCGCG with the antitumor drug netropsin has been reexamined to locate the drug accurately for computer-based drug design. The optimum solution is with the drug centered in the AATT region of the minor groove, making three good bifurcated hydrogen bonds with adenine N3 and thymine O2 atoms along the floor of the groove. Pyrrole rings of netropsin are packed against the C2 positions of adenines, leaving no room for the amine group of guanine and, hence, providing a structural rationale for the A.T specificity of netropsin. An alternative positioning in which the drug is shifted along the minor groove by ca. one-half base pair step is rejected on the basis of free R factor calculations and the appearance of the original drug-free difference maps. Final omit maps, although of more pleasing appearance, are not a dependable means of discriminating between right and wrong structures. The shifted alternative drug position ignores potential hydrogen bonding along the floor of the groove, provides no explanation for netropsin's observed A.T specificity, and is contradicted by NMR results [Patel, D. J. (1982) Proc. Natl. Acad. Sci. U.S.A. 79, 6424]. . Experimental Method is X-RAY DIFFRACTION . length a is 24.27 . length b is 39.62 . length c is 63.57 . angle alpha is 90.0 . angle beta is 90.0 . angle gamma is 90.0 . space group name H M is P 21 21 21 . ls d res high is 2.25 . ls R factor R work is is not available . ls R factor R free is 0.252 . ls R factor obs is 0.163 . Ligand name is ['MAGNESIUM ION', 'NETROPSIN'] . lig formula is ['Mg', 'C18 H26 N10 O3'] . lig inchi is ['JLVVSXFLKOJNIY-UHFFFAOYSA-N', 'IDBIFFKSXLYUOT-UHFFFAOYSA-N'] . UniProt id is is not available . source organism is is not available . Molecule is is not available . poly type is polydeoxyribonucleotide . poly rcsb entity polymer type is DNA . poly pdbx seq one letter code can is CGCGAATTCGCG . poly rcsb sample sequence length is 12.0 . mutation is 0.0 . chain is ['A', 'B'] . num chain is 2 . relese date is 1994-12-14 .
data_from_db  title is SPERM WHALE MYOGLOBIN F46V N-BUTYL ISOCYANIDE AT PH 9.0 . PubMed Abstract is is not available . Experimental Method is X-RAY DIFFRACTION . length a is 91.67 . length b is 91.67 . length c is 45.97 . angle alpha is 90.0 . angle beta is 90.0 . angle gamma is 120.0 . space group name H M is P 6 . ls d res high is 2.07 . ls R factor R work is 0.157 . ls R factor R free is 0.202 . ls R factor obs is 0.157 . Ligand name is ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING FE', 'N-BUTYL ISOCYANIDE'] . lig formula is ['O4 S', 'C34 H32 Fe N4 O4', 'C5 H9 N'] . lig inchi is ['QAOWNCQODCNURD-UHFFFAOYSA-L', 'KABFMIBPWCXCRK-RGGAHWMASA-L', 'FSBLVBBRXSCOKU-UHFFFAOYSA-N'] . UniProt id is P02185 . source organism is Physeter macrocephalus . Molecule is MYOGLOBIN . poly type is polypeptide(L) . poly rcsb entity polymer type is Protein . poly pdbx seq one letter code can is MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRVKHLKTEAEMKASEDLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGNFGADAQGAMNKALELFRKDIAAKYKELGYQG . poly rcsb sample sequence length is 154.0 . mutation is 2.0 . chain is ['A'] . num chain is 1 . relese date is 1997-12-13 .
data_from_db  title is SEQUENCE-DEPENDENT DRUG BINDING TO THE MINOR GROOVE OF DNA: THE CRYSTAL STRUCTURE OF THE DNA DODECAMER D(CGCAAATTTGCG)2 COMPLEXED WITH PROPAMIDINE . PubMed Abstract is The DNA-binding ligand propamidine, an analogue of the drug pentamidine which is used in the treatment of acquired immune deficiency syndrome (AIDS)-associated Pneumocystis carinii, has been cocrystallized with the DNA sequence d(CGCAAATTTGCG)2, and the crystal structure of the complex has been determined using data from 8 to 2.2 A resolution. The R factor converged to 15.5% with the inclusion of 73 water molecules. The structure shows binding of the propamidine molecule within the AT tract of the DNA minor groove with a shift from the center of the duplex toward the 3' end of ca. 2 A. The long AT tract of six base pairs in length allows the propamidine many potential binding sites in the DNA groove, and its binding is seen to occur where there is least perturbation to the DNA from that seen in the native structure. The interactions with bases are distinct from those previously observed for the sequence d(CGCGAATTCGCG)2. . Experimental Method is X-RAY DIFFRACTION . length a is 24.78 . length b is 41.16 . length c is 65.51 . angle alpha is 90.0 . angle beta is 90.0 . angle gamma is 90.0 . space group name H M is P 21 21 21 . ls d res high is 2.2 . ls R factor R work is 0.155 . ls R factor R free is is not available . ls R factor obs is 0.155 . Ligand name is ['1,3-BIS(AMIDINOPHENOXY)PROPANE'] . lig formula is ['C17 H20 N4 O2'] . lig inchi is ['WTFXJFJYEJZMFO-UHFFFAOYSA-N'] . UniProt id is is not available . source organism is is not available . Molecule is is not available . poly type is polydeoxyribonucleotide . poly rcsb entity polymer type is DNA . poly pdbx seq one letter code can is CGCAAATTTGCG . poly rcsb sample sequence length is 12.0 . mutation is 0.0 . chain is ['A', 'B'] . num chain is 2 . relese date is 1994-12-15 .
data_from_db  title is HOW AMINO-ACID INSERTIONS ARE ALLOWED IN AN ALPHA-HELIX OF T4 LYSOZYME . PubMed Abstract is Studies of extant protein sequences indicate that amino-acid insertions and deletions are preferentially located in loop regions, which has traditionally been explained as the result of selection removing deleterious mutations within secondary structural elements from the population. But there is no a priori reason to discount the possibility that insertions within secondary structure could either be tolerated until compensatory mutations arise, or have effects that are propagated away from secondary structure into loops. Earlier studies have indicated that insertions are generally tolerated, although much less well within secondary structure elements than in loop regions. Here we show that amino-acid insertions in an alpha-helix of T4 lysozyme can be accepted in two different ways. In some cases the inserted amino acids are accommodated within the helix, leading to the translocation of wild-type residues from the helix to the preceding loop. In other cases the insertion causes a 'looping-out' in the first or last turn of the helix. The individual structural responses seem to be dominated by the maintenance of the interface between the helix and the rest of the protein. . Experimental Method is X-RAY DIFFRACTION . length a is 60.9 . length b is 60.9 . length c is 96.1 . angle alpha is 90.0 . angle beta is 90.0 . angle gamma is 120.0 . space group name H M is P 32 2 1 . ls d res high is 1.74 . ls R factor R work is is not available . ls R factor R free is is not available . ls R factor obs is 0.174 . Ligand name is ['CHLORIDE ION', 'BETA-MERCAPTOETHANOL'] . lig formula is ['Cl', 'C2 H6 O S'] . lig inchi is ['VEXZGXHMUGYJMC-UHFFFAOYSA-M', 'DGVVWUTYPXICAM-UHFFFAOYSA-N'] . UniProt id is P00720 . source organism is Enterobacteria phage T4 . Molecule is T4 LYSOZYME . poly type is polypeptide(L) . poly rcsb entity polymer type is Protein . poly pdbx seq one letter code can is MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYKNL . poly rcsb sample sequence length is 165.0 . mutation is 0.0 . chain is ['A'] . num chain is 1 . relese date is 1992-09-29 .
Prepared 5 documents for embedding.
Chroma database found at './pdb_langchain_db'. Loading existing database.

C:\Users\rkuma\AppData\Local\Temp\ipykernel_1880\3558797967.py:90: LangChainDeprecationWarning: The class `Ollama` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the :class:`~langchain-ollama package and should be used instead. To use it run `pip install -U :class:`~langchain-ollama` and import as `from :class:`~langchain_ollama import OllamaLLM``.
  model = Ollama(model=OLLAMA_LLM_MODEL)

Chroma database loaded successfully.
Could not create or load the Chroma database. Retriever not available.
Initializing Ollama LLM with model: qwen2.5:7b...
Ollama LLM initialized successfully.

Ask your question:  100D

Your question: 100D

NameError: name 'retriever' is not defined

In [4]:
import os
from dotenv import load_dotenv
from langchain_community.document_loaders.csv_loader import CSVLoader
from langchain_community.embeddings import OllamaEmbeddings
from langchain_community.llms import Ollama
from langchain_community.vectorstores import Chroma
from langchain.chains import RetrievalQA

# Load environment variables (optional, for API keys if you were using hosted services)
load_dotenv()

# --- Configuration ---
CSV_FILE_PATH = "my_data.csv" # <--- IMPORTANT: Change this to your CSV file path
OLLAMA_LLM_MODEL = "llama3.2"
OLLAMA_EMBEDDING_MODEL = "mxbai-embed-large"
PERSIST_DIRECTORY = "./chroma_db" # Directory to store vector database (optional, for persistence)

def create_sample_csv(file_path):
    """Creates a sample CSV file if it doesn't exist."""
    if not os.path.exists(file_path):
        print(f"Creating a sample CSV: {file_path}")
        sample_data = """Name,Age,City,Occupation,Sales
Alice,30,New York,Engineer,150000
Bob,24,San Francisco,Designer,120000
Charlie,35,London,Doctor,180000
Diana,28,New York,Artist,90000
Eve,42,Paris,Manager,250000
Frank,30,London,Engineer,160000
Grace,27,New York,Designer,110000
Hannah,33,Paris,Doctor,190000
"""
        with open(file_path, 'w') as f:
            f.write(sample_data)
    else:
        print(f"Using existing CSV: {file_path}")

def main():
    """Main function to run the RAG process."""

    # 1. Create a sample CSV if it doesn't exist for easy testing
    create_sample_csv(CSV_FILE_PATH)

    print(f"--- Loading CSV data from {CSV_FILE_PATH} ---")
    # Using LangChain's CSVLoader to load the document
    # Each row in the CSV will typically become a separate Document object
    loader = CSVLoader(file_path=CSV_FILE_PATH)
    documents = loader.load()
    print(f"Loaded {len(documents)} documents (rows) from CSV.")

    print(f"--- Initializing Ollama Embeddings with '{OLLAMA_EMBEDDING_MODEL}' ---")
    # Initialize Ollama embeddings model
    embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)

    print(f"--- Creating Vector Store (ChromaDB) ---")
    # Create an in-memory ChromaDB vector store from the documents and embeddings
    # If you want persistence, uncomment persist_directory and vectorstore.persist()
    vectorstore = Chroma.from_documents(
        documents=documents,
        embedding=embeddings,
        # persist_directory=PERSIST_DIRECTORY # Uncomment to persist the database
    )
    # If using persistence, you can load it later with:
    # vectorstore = Chroma(persist_directory=PERSIST_DIRECTORY, embedding_function=embeddings)
    print("Vector store created.")

    print(f"--- Initializing Ollama LLM with '{OLLAMA_LLM_MODEL}' ---")
    # Initialize the Ollama LLM
    llm = Ollama(model=OLLAMA_LLM_MODEL)

    print(f"--- Setting up RetrievalQA Chain ---")
    # Create a RetrievalQA chain
    # This chain takes a question, retrieves relevant documents from the vectorstore,
    # and then passes them to the LLM to generate an answer.
    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff", # "stuff" means it puts all retrieved documents into the prompt
        retriever=vectorstore.as_retriever(),
        return_source_documents=True # Optional: to see which parts of CSV were used
    )
    print("RAG chain ready to answer questions.")

    print("\n--- Start asking questions! (Type 'exit' to quit) ---")
    while True:
        question = input("\nYour Question: ")
        if question.lower() == 'exit':
            break

        if not question.strip():
            print("Please enter a question.")
            continue

        print("Thinking...")
        try:
            # Invoke the RAG chain with the user's question
            response = qa_chain.invoke({"query": question})

            print("\n--- Answer ---")
            print(response["result"])

            if response.get("source_documents"):
                print("\n--- Source Documents (from CSV) ---")
                for doc in response["source_documents"]:
                    # Print the page_content which is the CSV row/chunk
                    print(f"- {doc.page_content}")
                    # You can also access metadata like original file path, row number etc.
                    # print(f"  (Source: {doc.metadata.get('source')}, Row: {doc.metadata.get('row')})")

        except Exception as e:
            print(f"An error occurred: {e}")
            print("Please ensure Ollama is running and the models are pulled.")

if __name__ == "__main__":
    main()

Creating a sample CSV: my_data.csv
--- Loading CSV data from my_data.csv ---
Loaded 8 documents (rows) from CSV.
--- Initializing Ollama Embeddings with 'mxbai-embed-large' ---
--- Creating Vector Store (ChromaDB) ---

C:\Users\rkuma\AppData\Local\Temp\ipykernel_4104\2418209214.py:52: LangChainDeprecationWarning: The class `OllamaEmbeddings` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the :class:`~langchain-ollama package and should be used instead. To use it run `pip install -U :class:`~langchain-ollama` and import as `from :class:`~langchain_ollama import OllamaEmbeddings``.
  embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)
C:\Users\rkuma\AppData\Local\Temp\ipykernel_4104\2418209214.py:68: LangChainDeprecationWarning: The class `Ollama` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the :class:`~langchain-ollama package and should be used instead. To use it run `pip install -U :class:`~langchain-ollama` and import as `from :class:`~langchain_ollama import OllamaLLM``.
  llm = Ollama(model=OLLAMA_LLM_MODEL)

Vector store created.
--- Initializing Ollama LLM with 'llama3.2' ---
--- Setting up RetrievalQA Chain ---
RAG chain ready to answer questions.

--- Start asking questions! (Type 'exit' to quit) ---

Your Question:  who have the large salary

Thinking...

--- Answer ---
Eve has the largest salary. She made $250,000 in sales.

--- Source Documents (from CSV) ---
- Name: Alice
Age: 30
City: New York
Occupation: Engineer
Sales: 150000
- Name: Frank
Age: 30
City: London
Occupation: Engineer
Sales: 160000
- Name: Eve
Age: 42
City: Paris
Occupation: Manager
Sales: 250000
- Name: Charlie
Age: 35
City: London
Occupation: Doctor
Sales: 180000

Your Question:  what is the best occupation

Thinking...

--- Answer ---
I don't know. The information provided doesn't give any indication of which occupation is considered "best" and success is often context-dependent on individual goals, values, and industry standards.

--- Source Documents (from CSV) ---
- Name: Alice
Age: 30
City: New York
Occupation: Engineer
Sales: 150000
- Name: Frank
Age: 30
City: London
Occupation: Engineer
Sales: 160000
- Name: Bob
Age: 24
City: San Francisco
Occupation: Designer
Sales: 120000
- Name: Charlie
Age: 35
City: London
Occupation: Doctor
Sales: 180000

Your Question:  exit

In [4]:
import os
from dotenv import load_dotenv
from langchain_community.document_loaders.csv_loader import CSVLoader
from langchain_community.embeddings import OllamaEmbeddings
from langchain_community.llms import Ollama
from langchain_community.vectorstores import Chroma
from langchain.chains import RetrievalQA

In [5]:
data_test=pd.read_csv('2k_input_data_pdb.csv')
data_test=data_test.head(100)
data_test

,rcsb_id,pubmed_id,title,PubMed Abstract,Experimental Method,length_a,length_b,length_c,angle_alpha,angle_beta,...,source_organism,Molecule,poly_type,poly_rcsb_entity_polymer_type,poly_pdbx_seq_one_letter_code_can,poly_rcsb_sample_sequence_length,mutation,chain,num_chain,relese_date
0,100D,7816639.0,CRYSTAL STRUCTURE OF THE HIGHLY DISTORTED CHIM...,The crystal structure of the self-complementar...,X-RAY DIFFRACTION,23.98,40.77,44.84,90.0,90.0,...,is not available,is not available,polydeoxyribonucleotide/polyribonucleotide hybrid,NA-hybrid,CCGGCGCCGG,10.0,0.0,"['A', 'B']",2,1994-12-05
1,101D,7711020.0,REFINEMENT OF NETROPSIN BOUND TO DNA: BIAS AND...,The X-ray crystal structure of the complex of ...,X-RAY DIFFRACTION,24.27,39.62,63.57,90.0,90.0,...,is not available,is not available,polydeoxyribonucleotide,DNA,CGCGAATTCGCG,12.0,0.0,"['A', 'B']",2,1994-12-14
2,101M,is not available,SPERM WHALE MYOGLOBIN F46V N-BUTYL ISOCYANIDE ...,is not available,X-RAY DIFFRACTION,91.67,91.67,45.97,90.0,90.0,...,Physeter macrocephalus,MYOGLOBIN,polypeptide(L),Protein,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...,154.0,2.0,['A'],1,1997-12-13
3,102D,7608897.0,SEQUENCE-DEPENDENT DRUG BINDING TO THE MINOR G...,"The DNA-binding ligand propamidine, an analogu...",X-RAY DIFFRACTION,24.78,41.16,65.51,90.0,90.0,...,is not available,is not available,polydeoxyribonucleotide,DNA,CGCAAATTTGCG,12.0,0.0,"['A', 'B']",2,1994-12-15
4,102L,8429913.0,HOW AMINO-ACID INSERTIONS ARE ALLOWED IN AN AL...,Studies of extant protein sequences indicate t...,X-RAY DIFFRACTION,60.9,60.9,96.1,90.0,90.0,...,Enterobacteria phage T4,T4 LYSOZYME,polypeptide(L),Protein,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSE...,165.0,0.0,['A'],1,1992-09-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,140D,8257678.0,SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE...,The three-dimensional solution structure of a ...,SOLUTION NMR,is not available,is not available,is not available,is not available,is not available,...,is not available,is not available,polydeoxyribonucleotide,DNA,AGCTTGCCTTGAG,13.0,0.0,['A'],1,1993-09-24
96,140L,8259514.0,ROLE OF BACKBONE FLEXIBILITY IN THE ACCOMMODAT...,To understand better how the packing of side c...,X-RAY DIFFRACTION,61.1,61.1,96.8,90.0,90.0,...,Enterobacteria phage T4,T4 LYSOZYME,polypeptide(L),Protein,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...,164.0,0.0,['A'],1,1993-10-15
97,141D,8257678.0,SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE...,The three-dimensional solution structure of a ...,SOLUTION NMR,is not available,is not available,is not available,is not available,is not available,...,is not available,is not available,polydeoxyribonucleotide,DNA,AGCTTGCCTTGAG,13.0,0.0,['A'],1,1993-09-24
98,141L,8259514.0,ROLE OF BACKBONE FLEXIBILITY IN THE ACCOMMODAT...,To understand better how the packing of side c...,X-RAY DIFFRACTION,61.0,61.0,96.9,90.0,90.0,...,Enterobacteria phage T4,T4 LYSOZYME,polypeptide(L),Protein,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...,164.0,0.0,['A'],1,1993-10-15
99,142D,8257678.0,SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE...,The three-dimensional solution structure of a ...,SOLUTION NMR,is not available,is not available,is not available,is not available,is not available,...,is not available,is not available,polydeoxyribonucleotide,DNA,AGCTTGCCTTGAG,13.0,0.0,['A'],1,1993-09-24

In [7]:
data_test.to_csv('100_data.csv',index=False)

In [13]:
load_dotenv()

# --- Configuration ---
CSV_FILE_PATH = '2k_input_data_pdb.csv' # <--- IMPORTANT: Change this to your CSV file path
CSV_FILE_PATH = '100_data.csv'
OLLAMA_LLM_MODEL = "llama3.1"
OLLAMA_EMBEDDING_MODEL = "mxbai-embed-large"
PERSIST_DIRECTORY = "./chroma_db3" # Directory to store vector database (optional, for persistence)

In [14]:
# create_sample_csv(CSV_FILE_PATH)
# loader = CSVLoader(file_path=CSV_FILE_PATH)
# documents = loader.load()
# documents

In [15]:



def main():
    """Main function to run the RAG process."""
    # 1. Create a sample CSV if it doesn't exist for easy testing
    # create_sample_csv(CSV_FILE_PATH)
    loader = CSVLoader(file_path=CSV_FILE_PATH)
    documents = loader.load()
    print(f"Loaded {len(documents)} documents (rows) from CSV.")
    embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)


    vectorstore = Chroma.from_documents(
        documents=documents,
        embedding=embeddings,

    )

    print("Vector store created.")

    llm = Ollama(model=OLLAMA_LLM_MODEL)

    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff", # "stuff" means it puts all retrieved documents into the prompt
        retriever=vectorstore.as_retriever(),
        return_source_documents=True # Optional: to see which parts of CSV were used
    )
    print("RAG chain ready to answer questions.")

    print("\n--- Start asking questions! (Type 'exit' to quit) ---")
    while True:
        question = input("\nYour Question: ")
        if question.lower() == 'exit':
            break

        if not question.strip():
            print("Please enter a question.")
            continue

        print("Thinking...")
        try:
            # Invoke the RAG chain with the user's question
            response = qa_chain.invoke({"query": question})

            print("\n--- Answer ---")
            print(response["result"])

            if response.get("source_documents"):
                print("\n--- Source Documents (from CSV) ---")
                for doc in response["source_documents"]:
                    print(f"- {doc.page_content}")


        except Exception as e:
            print(f"An error occurred: {e}")
            print("Please ensure Ollama is running and the models are pulled.")

if __name__ == "__main__":
    main()

Loaded 100 documents (rows) from CSV.
Vector store created.
RAG chain ready to answer questions.

--- Start asking questions! (Type 'exit' to quit) ---

Your Question:  100D

Thinking...

--- Answer ---
I don't know what the question "100D" is, as there isn't any information provided about it in the given context.

--- Source Documents (from CSV) ---
- rcsb_id: 109M
pubmed_id: is not available
title: SPERM WHALE MYOGLOBIN D122N ETHYL ISOCYANIDE AT PH 9.0
PubMed Abstract: is not available
Experimental Method: X-RAY DIFFRACTION
length_a: 91.486
length_b: 91.486
length_c: 45.874
angle_alpha: 90.0
angle_beta: 90.0
angle_gamma: 120.0
space_group_name_H_M: P 6
ls_d_res_high: 1.83
ls_R_factor_R_work: 0.148
ls_R_factor_R_free: 0.212
ls_R_factor_obs: 0.148
Ligand_name: ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING FE', 'ETHYL ISOCYANIDE']
lig_formula: ['O4 S', 'C34 H32 Fe N4 O4', 'C3 H6 N']
lig_inchi: ['QAOWNCQODCNURD-UHFFFAOYSA-L', 'KABFMIBPWCXCRK-RGGAHWMASA-L', 'JEGVKBYNUPNGJU-UHFFFAOYSA-N']
UniProt_id: P02185
source_organism: Physeter macrocephalus
Molecule: MYOGLOBIN
poly_type: polypeptide(L)
poly_rcsb_entity_polymer_type: Protein
poly_pdbx_seq_one_letter_code_can: MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRFKHLKTEAEMKASEDLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGNFGADAQGAMNKALELFRKDIAAKYKELGYQG
poly_rcsb_sample_sequence_length: 154.0
mutation: 1.0
chain: ['A']
num_chain: 1
relese_date: 1997-12-22
- rcsb_id: 109M
pubmed_id: is not available
title: SPERM WHALE MYOGLOBIN D122N ETHYL ISOCYANIDE AT PH 9.0
PubMed Abstract: is not available
Experimental Method: X-RAY DIFFRACTION
length_a: 91.486
length_b: 91.486
length_c: 45.874
angle_alpha: 90.0
angle_beta: 90.0
angle_gamma: 120.0
space_group_name_H_M: P 6
ls_d_res_high: 1.83
ls_R_factor_R_work: 0.148
ls_R_factor_R_free: 0.212
ls_R_factor_obs: 0.148
Ligand_name: ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING FE', 'ETHYL ISOCYANIDE']
lig_formula: ['O4 S', 'C34 H32 Fe N4 O4', 'C3 H6 N']
lig_inchi: ['QAOWNCQODCNURD-UHFFFAOYSA-L', 'KABFMIBPWCXCRK-RGGAHWMASA-L', 'JEGVKBYNUPNGJU-UHFFFAOYSA-N']
UniProt_id: P02185
source_organism: Physeter macrocephalus
Molecule: MYOGLOBIN
poly_type: polypeptide(L)
poly_rcsb_entity_polymer_type: Protein
poly_pdbx_seq_one_letter_code_can: MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRFKHLKTEAEMKASEDLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGNFGADAQGAMNKALELFRKDIAAKYKELGYQG
poly_rcsb_sample_sequence_length: 154.0
mutation: 1.0
chain: ['A']
num_chain: 1
relese_date: 1997-12-22
- rcsb_id: 105M
pubmed_id: is not available
title: SPERM WHALE MYOGLOBIN N-BUTYL ISOCYANIDE AT PH 9.0
PubMed Abstract: is not available
Experimental Method: X-RAY DIFFRACTION
length_a: 64.72
length_b: 30.061
length_c: 35.191
angle_alpha: 90.0
angle_beta: 105.76
angle_gamma: 90.0
space_group_name_H_M: P 1 21 1
ls_d_res_high: 2.02
ls_R_factor_R_work: 0.174
ls_R_factor_R_free: 0.268
ls_R_factor_obs: 0.174
Ligand_name: ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING FE', 'N-BUTYL ISOCYANIDE']
lig_formula: ['O4 S', 'C34 H32 Fe N4 O4', 'C5 H9 N']
lig_inchi: ['QAOWNCQODCNURD-UHFFFAOYSA-L', 'KABFMIBPWCXCRK-RGGAHWMASA-L', 'FSBLVBBRXSCOKU-UHFFFAOYSA-N']
UniProt_id: P02185
source_organism: Physeter macrocephalus
Molecule: MYOGLOBIN
poly_type: polypeptide(L)
poly_rcsb_entity_polymer_type: Protein
poly_pdbx_seq_one_letter_code_can: VLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRFKHLKTEAEMKASEDLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGDFGADAQGAMNKALELFRKDIAAKYKELGYQG
poly_rcsb_sample_sequence_length: 153.0
mutation: 0.0
chain: ['A']
num_chain: 1
relese_date: 1997-12-18
- rcsb_id: 105M
pubmed_id: is not available
title: SPERM WHALE MYOGLOBIN N-BUTYL ISOCYANIDE AT PH 9.0
PubMed Abstract: is not available
Experimental Method: X-RAY DIFFRACTION
length_a: 64.72
length_b: 30.061
length_c: 35.191
angle_alpha: 90.0
angle_beta: 105.76
angle_gamma: 90.0
space_group_name_H_M: P 1 21 1
ls_d_res_high: 2.02
ls_R_factor_R_work: 0.174
ls_R_factor_R_free: 0.268
ls_R_factor_obs: 0.174
Ligand_name: ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING FE', 'N-BUTYL ISOCYANIDE']
lig_formula: ['O4 S', 'C34 H32 Fe N4 O4', 'C5 H9 N']
lig_inchi: ['QAOWNCQODCNURD-UHFFFAOYSA-L', 'KABFMIBPWCXCRK-RGGAHWMASA-L', 'FSBLVBBRXSCOKU-UHFFFAOYSA-N']
UniProt_id: P02185
source_organism: Physeter macrocephalus
Molecule: MYOGLOBIN
poly_type: polypeptide(L)
poly_rcsb_entity_polymer_type: Protein
poly_pdbx_seq_one_letter_code_can: VLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRFKHLKTEAEMKASEDLKKHGVTVLTALGAILKKKGHHEAELKPLAQSHATKHKIPIKYLEFISEAIIHVLHSRHPGDFGADAQGAMNKALELFRKDIAAKYKELGYQG
poly_rcsb_sample_sequence_length: 153.0
mutation: 0.0
chain: ['A']
num_chain: 1
relese_date: 1997-12-18

Your Question:  exit

In [17]:

# --- Configuration ---
CSV_FILE_PATH = "my_bio_data.csv" # Make sure this path is correct
OLLAMA_EMBEDDING_MODEL = "nomic-embed-text" # Or a more specialized bio-embedding model if available
OLLAMA_LLM_MODEL = "llama3.1" # Or "mistral", "mixtral", etc.

# --- Define the column(s) to use as page_content and metadata ---
CONTENT_COLUMN = "Description" # The column whose content will be the main text for embedding
METADATA_COLUMNS = ["Product", "Category", "Price"] # Columns to add as metadata

def create_sample_csv(file_path):
    """Creates a sample CSV file for testing with bio-like data."""
    if not os.path.exists(file_path):
        data = {
            "Product": ["Insulin", "Adrenaline", "Collagen", "Hemoglobin", "Antibody_X"],
            "Category": ["Hormone", "Hormone", "Protein", "Protein", "Immunoglobulin"],
            "Price": [120, 50, 80, 150, 300], # Fictitious prices
            "Sequence_Length": [51, 8, 1000, 141, 1500], # Fictitious data
            "Description": [
                "A peptide hormone produced by beta cells of the pancreatic islets; essential for regulating carbohydrate and fat metabolism in the body.",
                "A hormone and neurotransmitter involved in regulating visceral functions (e.g., fight-or-flight response).",
                "The main structural protein in the extracellular matrix of various connective tissues.",
                "A protein in red blood cells that carries oxygen from the lungs to the body's tissues and returns carbon dioxide to the lungs.",
                "A large Y-shaped protein used by the immune system to identify and neutralize foreign objects like bacteria and viruses."
            ]
        }
        df = pd.DataFrame(data)
        df.to_csv(file_path, index=False)
        print(f"Sample CSV '{file_path}' created.")
    else:
        print(f"CSV file '{file_path}' already exists.")

def load_documents_with_metadata(file_path, content_column, metadata_columns):
    """
    Loads CSV data into LangChain Documents, explicitly setting page_content
    and adding specified columns as metadata.
    """
    df = pd.read_csv(file_path)
    documents = []
    for index, row in df.iterrows():
        page_content = str(row[content_column]) # Ensure content is string
        metadata = {"row_index": index} # Always good to have row index

        # Add specified metadata columns
        for col in metadata_columns:
            if col in row: # Check if column exists in the row
                metadata[col] = row[col]

        doc = Document(page_content=page_content, metadata=metadata)
        documents.append(doc)
    return documents

def main():
    """Main function to run the RAG process."""
    create_sample_csv(CSV_FILE_PATH)

    # --- Modified Document Loading ---
    documents = load_documents_with_metadata(CSV_FILE_PATH, CONTENT_COLUMN, METADATA_COLUMNS)
    print(f"Loaded {len(documents)} documents (rows) from CSV.")

    # --- Debugging: Inspect loaded documents with metadata ---
    print("\n--- Sample of loaded document content and metadata ---")
    for i, doc in enumerate(documents[:2]): # Print first 2 documents
        print(f"Document {i+1}:\n")
        print(f"  Page Content: {doc.page_content}")
        print(f"  Metadata: {doc.metadata}\n---")
    print("---------------------------------------")

    embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)

    vectorstore = Chroma.from_documents(
        documents=documents,
        embedding=embeddings,
    )

    print("Vector store created.")

    llm = Ollama(model=OLLAMA_LLM_MODEL)

    retriever = vectorstore.as_retriever(search_kwargs={"k": 5})

    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=retriever,
        return_source_documents=True
    )
    print("RAG chain ready to answer questions.")

    print("\n--- Start asking questions! (Type 'exit' to quit) ---")
    while True:
        question = input("\nYour Question: ")
        if question.lower() == 'exit':
            break

        if not question.strip():
            print("Please enter a question.")
            continue

        print("Thinking...")
        try:
            response = qa_chain.invoke({"query": question})

            print("\n--- Answer ---")
            print(response["result"])

            if response.get("source_documents"):
                print("\n--- Source Documents (from CSV) ---")
                for doc in response["source_documents"]:
                    print(f"- Content: {doc.page_content}")
                    print(f"  Metadata: {doc.metadata}") # Metadata will now include your specified columns
                print("-------------------------------------")

        except Exception as e:
            print(f"An error occurred: {e}")
            print("Please ensure Ollama is running and the models are pulled.")
            print("Also check for context window limitations if the error persists.")

if __name__ == "__main__":
    main()

CSV file 'my_bio_data.csv' already exists.
Loaded 5 documents (rows) from CSV.

--- Sample of loaded document content and metadata ---
Document 1:

  Page Content: A peptide hormone produced by beta cells of the pancreatic islets; essential for regulating carbohydrate and fat metabolism in the body.
  Metadata: {'row_index': 0, 'Product': 'Insulin', 'Category': 'Hormone', 'Price': 120}
---
Document 2:

  Page Content: A hormone and neurotransmitter involved in regulating visceral functions (e.g., fight-or-flight response).
  Metadata: {'row_index': 1, 'Product': 'Adrenaline', 'Category': 'Hormone', 'Price': 50}
---
---------------------------------------

InvalidArgumentError: Collection expecting embedding with dimension of 1024, got 768

In [8]:
CSV_FILE_PATH = '2k_input_data_pdb.csv' # <--- IMPORTANT: Change this to your CSV file path
CSV_FILE_PATH = '100_data.csv'
OLLAMA_LLM_MODEL = "llama3.1"
OLLAMA_EMBEDDING_MODEL = "mxbai-embed-large"
PERSIST_DIRECTORY = "./pdb_test1" # Directory to store vector database (optional, for persistence)

In [35]:
data7=pd.read_csv('100_data.csv') 
data7
comp_100=[]
ids=[]
for i in range(len(data7)):
    sentance=''
    for j in range(1,len(data7.columns)):
        sentance = str(sentance)+str(data7.columns[j])+' is '+str(data7.iloc[i,j])+' .'
    comp_100.append(sentance)
    ids.append(data7.iloc[i,0])

In [40]:
for ind, content in enumerate(comp_100):
    print(content)
    doc = Document(
        page_content=content,
        metadata={'rcsb_id':ids[ind]})
    documents.append(doc)

pubmed_id is 7816639.0 .title is CRYSTAL STRUCTURE OF THE HIGHLY DISTORTED CHIMERIC DECAMER R(C)D(CGGCGCCG)R(G)-SPERMINE COMPLEX-SPERMINE BINDING TO PHOSPHATE ONLY AND MINOR GROOVE TERTIARY BASE-PAIRING .PubMed Abstract is The crystal structure of the self-complementary chimeric decamer duplex r(C)d(CGGCGCCG)r(G), with RNA base pairs at both termini, has been solved at 1.9 A resolution by the molecular replacement method and refined to an R value of 0.145 for 2,314 reflections. The C3'-endo sugar puckers of the terminal riboses apparently drive the entire chimeric duplex into an A-DNA conformation, in contrast to the B-DNA conformation adopted by the all-deoxy decamer of the same sequence. Five symmetry related duplexes encapsulate a spermine molecule which interacts with ten phosphate groups, both directly and through water molecules to form multiple ionic and hydrogen bonding interactions. The spermine interaction severely bends the duplexes by 31 degrees into the major groove at the fourth base pair G(4).C(17), jolts it and slides the 'base plate' into the minor groove. This base pair, together with the adjacent base pair in the top half and the corresponding pseudo two-fold related base pairs in the bottom half, form four minor groove base-paired multiples with the terminal base pairs of two neighboring duplexes. .Experimental Method is X-RAY DIFFRACTION .length_a is 23.98 .length_b is 40.77 .length_c is 44.84 .angle_alpha is 90.0 .angle_beta is 90.0 .angle_gamma is 90.0 .space_group_name_H_M is P 21 21 21 .ls_d_res_high is 1.9 .ls_R_factor_R_work is 0.145 .ls_R_factor_R_free is is not available .ls_R_factor_obs is 0.145 .Ligand_name is ['SPERMINE'] .lig_formula is ['C10 H26 N4'] .lig_inchi is ['PFNFFQXMRSDOHW-UHFFFAOYSA-N'] .UniProt_id is is not available .source_organism is is not available .Molecule is is not available .poly_type is polydeoxyribonucleotide/polyribonucleotide hybrid .poly_rcsb_entity_polymer_type is NA-hybrid .poly_pdbx_seq_one_letter_code_can is CCGGCGCCGG .poly_rcsb_sample_sequence_length is 10.0 .mutation is 0.0 .chain is ['A', 'B'] .num_chain is 2 .relese_date is 1994-12-05 .

NameError: name 'documents' is not defined

In [39]:
data7 = pd.read_csv('100_data.csv')
data7

,rcsb_id,pubmed_id,title,PubMed Abstract,Experimental Method,length_a,length_b,length_c,angle_alpha,angle_beta,...,source_organism,Molecule,poly_type,poly_rcsb_entity_polymer_type,poly_pdbx_seq_one_letter_code_can,poly_rcsb_sample_sequence_length,mutation,chain,num_chain,relese_date
0,100D,7816639.0,CRYSTAL STRUCTURE OF THE HIGHLY DISTORTED CHIM...,The crystal structure of the self-complementar...,X-RAY DIFFRACTION,23.98,40.77,44.84,90.0,90.0,...,is not available,is not available,polydeoxyribonucleotide/polyribonucleotide hybrid,NA-hybrid,CCGGCGCCGG,10.0,0.0,"['A', 'B']",2,1994-12-05
1,101D,7711020.0,REFINEMENT OF NETROPSIN BOUND TO DNA: BIAS AND...,The X-ray crystal structure of the complex of ...,X-RAY DIFFRACTION,24.27,39.62,63.57,90.0,90.0,...,is not available,is not available,polydeoxyribonucleotide,DNA,CGCGAATTCGCG,12.0,0.0,"['A', 'B']",2,1994-12-14
2,101M,is not available,SPERM WHALE MYOGLOBIN F46V N-BUTYL ISOCYANIDE ...,is not available,X-RAY DIFFRACTION,91.67,91.67,45.97,90.0,90.0,...,Physeter macrocephalus,MYOGLOBIN,polypeptide(L),Protein,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...,154.0,2.0,['A'],1,1997-12-13
3,102D,7608897.0,SEQUENCE-DEPENDENT DRUG BINDING TO THE MINOR G...,"The DNA-binding ligand propamidine, an analogu...",X-RAY DIFFRACTION,24.78,41.16,65.51,90.0,90.0,...,is not available,is not available,polydeoxyribonucleotide,DNA,CGCAAATTTGCG,12.0,0.0,"['A', 'B']",2,1994-12-15
4,102L,8429913.0,HOW AMINO-ACID INSERTIONS ARE ALLOWED IN AN AL...,Studies of extant protein sequences indicate t...,X-RAY DIFFRACTION,60.9,60.9,96.1,90.0,90.0,...,Enterobacteria phage T4,T4 LYSOZYME,polypeptide(L),Protein,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSE...,165.0,0.0,['A'],1,1992-09-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,140D,8257678.0,SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE...,The three-dimensional solution structure of a ...,SOLUTION NMR,is not available,is not available,is not available,is not available,is not available,...,is not available,is not available,polydeoxyribonucleotide,DNA,AGCTTGCCTTGAG,13.0,0.0,['A'],1,1993-09-24
96,140L,8259514.0,ROLE OF BACKBONE FLEXIBILITY IN THE ACCOMMODAT...,To understand better how the packing of side c...,X-RAY DIFFRACTION,61.1,61.1,96.8,90.0,90.0,...,Enterobacteria phage T4,T4 LYSOZYME,polypeptide(L),Protein,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...,164.0,0.0,['A'],1,1993-10-15
97,141D,8257678.0,SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE...,The three-dimensional solution structure of a ...,SOLUTION NMR,is not available,is not available,is not available,is not available,is not available,...,is not available,is not available,polydeoxyribonucleotide,DNA,AGCTTGCCTTGAG,13.0,0.0,['A'],1,1993-09-24
98,141L,8259514.0,ROLE OF BACKBONE FLEXIBILITY IN THE ACCOMMODAT...,To understand better how the packing of side c...,X-RAY DIFFRACTION,61.0,61.0,96.9,90.0,90.0,...,Enterobacteria phage T4,T4 LYSOZYME,polypeptide(L),Protein,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSEL...,164.0,0.0,['A'],1,1993-10-15
99,142D,8257678.0,SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE...,The three-dimensional solution structure of a ...,SOLUTION NMR,is not available,is not available,is not available,is not available,is not available,...,is not available,is not available,polydeoxyribonucleotide,DNA,AGCTTGCCTTGAG,13.0,0.0,['A'],1,1993-09-24

In [9]:
data7 = pd.read_csv('100_data.csv')
documents = []

for index, row in data7.iterrows():
    doc_id = row.iloc[0]
    sentence_parts = []
    for col_name, value in row.items():
        if col_name == data7.columns[0]: # Skip the ID column
            continue
        sentence_parts.append(f"{col_name} is {value}.")
    page_content = " ".join(sentence_parts)

    metadata = {
        "id": doc_id,         # The ID from the first column
        "row_number": index,
    }


doc = Document(
    page_content=page_content,
    metadata=metadata
)
documents.append(doc)

In [11]:
# if documents:
db = Chroma.from_documents(
    documents=documents,
    embedding=OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL),
    persist_directory=PERSIST_DIRECTORY
)
# db.persist()

C:\Users\rkuma\AppData\Local\Temp\ipykernel_11972\3555464889.py:4: LangChainDeprecationWarning: The class `OllamaEmbeddings` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the :class:`~langchain-ollama package and should be used instead. To use it run `pip install -U :class:`~langchain-ollama` and import as `from :class:`~langchain_ollama import OllamaEmbeddings``.
  embedding=OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL),

In [12]:

if db:
    retriever = db.as_retriever(search_kwargs={'k':3})
    print("Retriever successfully created from the Chroma database!")
else:
    print("Could not create or load the Chroma database. Retriever not available.")
    exit()
    

try:
    model = Ollama(model=OLLAMA_LLM_MODEL)
    print("Ollama LLM initialized successfully.")
except Exception as e:
    print(f"Error initializing Ollama LLM: {e}")
    exit()

Retriever successfully created from the Chroma database!
Ollama LLM initialized successfully.

C:\Users\rkuma\AppData\Local\Temp\ipykernel_11972\3370241976.py:10: LangChainDeprecationWarning: The class `Ollama` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the :class:`~langchain-ollama package and should be used instead. To use it run `pip install -U :class:`~langchain-ollama` and import as `from :class:`~langchain_ollama import OllamaLLM``.
  model = Ollama(model=OLLAMA_LLM_MODEL)

In [13]:

template = """
You are an expert in answering questions about a bio infomatics  based on provided data about proteins.

Here are some relevant protein data:
{reviews}

Here is the question to answer: {question}
"""
prompt = ChatPromptTemplate.from_template(template)
chain = prompt | model


while True:
    question = input('Ask your question: ')
    print(f"Your question: {question}") 

    if question.lower() == 'q':
        print("Exiting Q&A session.")
        break
    else:
        retrieved_docs = retriever.invoke(question)
        formatted_reviews = "\n\n".join([doc.page_content for doc in retrieved_docs])
        print('formatted_reviews',formatted_reviews)

        result = chain.invoke({'reviews': formatted_reviews, 'question': question})

        # Step 3: Print the result from the LLM
        print("\n--- LLM Response ---")
        print(result) # For Ollama, the result is usually a string directly
        print("---------------------\n")

Ask your question:  what is 100D

Your question: what is 100D
formatted_reviews pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

--- LLM Response ---
I don't see any information related to "100D" in the provided protein data. The data appears to be about a DNA sequence (d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT)) and its solution structure determined by NMR spectroscopy.

If you meant something else by "100D", please clarify or provide more context so I can assist you better.
---------------------

Ask your question:  rcsb id 100D

Your question: rcsb id 100D
formatted_reviews pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

--- LLM Response ---
Unfortunately, I don't see any data related to a "rcsb id 100D" in the provided text. The text appears to be about a study on the solution structure of a trisdecamer DNA duplex sequence from the HIV-1 genome.

However, if you're asking for information about PDB entry 1DDX (which is mentioned as an rcsb id in one of the duplicated sections), I can try to provide some information.

1DDX is indeed a protein structure, not DNA. According to its pdb file description, it's a "Solution NMR Structure of HIV-1 Integrase Bound to Viral DNA", solved by solution nuclear magnetic resonance (NMR) spectroscopy.

If you have any specific questions about the 1DDX structure or would like more information, feel free to ask!
---------------------

Ask your question:  exit

Your question: exit
formatted_reviews pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

--- LLM Response ---
It seems you provided a large amount of text and asked me to "exit". I'm happy to help with any questions about bioinformatics based on the protein data you provided, but it looks like you didn't actually ask a question.

If you'd like, I can summarize the information in the text you provided. It appears to be an article about the solution structure of a conserved DNA sequence from the HIV-1 genome, determined using NMR spectroscopy and restrained molecular dynamics calculations.

Please feel free to ask a specific question related to bioinformatics or protein structure, and I'll do my best to provide an answer!
---------------------

Ask your question:

Your question:
formatted_reviews pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

pubmed_id is 8257678.0. title is SOLUTION STRUCTURE OF A CONSERVED DNA SEQUENCE FROM THE HIV-1 GENOME: RESTRAINED MOLECULAR DYNAMICS SIMULATION WITH DISTANCE AND TORSION ANGLE RESTRAINTS DERIVED FROM TWO-DIMENSIONAL NMR SPECTRA. PubMed Abstract is The three-dimensional solution structure of a trisdecamer DNA duplex sequence, d(AGCTTGCCTTGAG).d(CTCAAGGCAAGCT), from a conserved region of HIV-1 genome's long terminal repeat, has been investigated using NMR spectroscopy and restrained molecular dynamics calculations. Interproton distances derived from two-dimensional nuclear Overhauser enhancement (2D NOE) experiments, using the iterative complete relaxation matrix algorithm MARDIGRAS, and torsion angles for sugar rings, estimated from stimulated fitting of double-quantum-filtered correlation (2QF-COSY) spectra, were obtained [Mujeeb, A., Kerwin, S. M., Egan, W. M., Kenyon, G. L., & James, T. L. (1992) Biochemistry 31, 9325-38]. These structural restraints have now been employed as the basis for structure refinement using restrained molecular dynamics (rMD) to search conformational space for structures consistent with the experimental restraints. Specifically, upper and lower bounds on the restraints were incorporated into the AMBER (version 4.0) total potential energy function of the system, the bounds being used to define the width of a flat-well penalty term in the AMBER force field. Confidence in the time-averaged structure obtained is engendered by convergence to essentially the same structure (root-mean-square deviation approximately 0.9 A) when two quite different DNA models, A-DNA and B-DNA (RMSD approximately 6.5 A), were employed as starting structures and when various initial trajectories were used for the rMD runs. The derived structure is further supported by the total energy calculated, the restraint violation energy, the restraint deviations, and the fit with experimental data. For the latter, the sixth-root residual index indicated a good fit of the determined structure with experimental 2D NOE spectral intensities (R1x < 0.07), and the RMS difference between vicinal proton coupling constants calculated for the derived structure and experimental coupling constants were also in reasonable agreement (JRMS = 0.9 Hz). While the structure of the trisdecamer is basically in the B-DNA family, some structural parameters manifest interesting local variations. The helix parameters indicate that, compared with classical B-DNA, the structure is longitudinally more compressed. Local structural variations at the two TG steps in particular together create bending into the major groove of the duplex. Comparison of the two-CTTG-tetrads in the duplex reveals that they have similar structures, with the TT moieties being almost identical; however, the -CTTG-pur sequence has a larger roll and slide for the -TG- step than for the -CTTG-pyr sequence, in accord with published X-ray crystallographic conclusions.. Experimental Method is SOLUTION NMR. length_a is is not available. length_b is is not available. length_c is is not available. angle_alpha is is not available. angle_beta is is not available. angle_gamma is is not available. space_group_name_H_M is is not available. ls_d_res_high is is not available. ls_R_factor_R_work is is not available. ls_R_factor_R_free is is not available. ls_R_factor_obs is is not available. Ligand_name is is not available. lig_formula is is not available. lig_inchi is is not available. UniProt_id is is not available. source_organism is is not available. Molecule is is not available. poly_type is polydeoxyribonucleotide. poly_rcsb_entity_polymer_type is DNA. poly_pdbx_seq_one_letter_code_can is AGCTTGCCTTGAG. poly_rcsb_sample_sequence_length is 13.0. mutation is 0.0. chain is ['A']. num_chain is 1. relese_date is 1993-09-24.

KeyboardInterrupt:

In [14]:
import pandas as pd
from langchain_community.document_loaders import CSVLoader
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import OllamaEmbeddings
from langchain_community.llms import Ollama
from langchain.chains import RetrievalQA
import os

In [15]:
CSV_FILE_PATH = '100_data.csv' # Replace with your CSV file path
# data7 = pd.read_csv()
OLLAMA_EMBEDDING_MODEL = 'mxbai-embed-large' # Or 'nomic-embed-text', etc.
OLLAMA_LLM_MODEL = 'llama3.2'
VECTOR_DB_PATH = './chroma_db' # Directory to store your vector database


df = pd.read_csv(CSV_FILE_PATH)

df['rag_content'] = df.apply(
    lambda row: f"rcsb_id: {row['rcsb_id']}\n"
                f"pubmed_id: {row['pubmed_id']}\n"
                f"title: {row['title']}\n"
                f"PubMed Abstract: {row['PubMed Abstract']}\n"
                f"Ligand_name: {row['Ligand_name']}",
    axis=1
)


from langchain.schema import Document

documents = []
for index, row in df.iterrows():
    doc = Document(
        page_content=row['rag_content'],
        metadata={
            'source': CSV_FILE_PATH,
            'row_id': index,
            'rcsb_id': row['rcsb_id'], # Keep original metadata for filtering if needed
            # Add other relevant metadata here
        }
    )
    documents.append(doc)

print(f"Loaded {len(documents)} documents from the CSV.")
# Optional: Print a sample document
# print("\nSample Document:")
# print(documents[0].page_content)
# print(documents[0].metadata)


# --- 2. Initialize Ollama Embedding Model ---
print(f"Initializing embedding model: {OLLAMA_EMBEDDING_MODEL}...")
embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)

# --- 3. Create and Persist Vector Store (ChromaDB) ---
print(f"Creating/Loading Vector Store at: {VECTOR_DB_PATH}...")
# This will create a new ChromaDB or load an existing one
# If the directory exists, it will load; otherwise, it will create.
vectorstore = Chroma.from_documents(
    documents=documents,
    embedding=embeddings,
    persist_directory=VECTOR_DB_PATH
)
print("Vector store ready.")

# Persist the collection
vectorstore.persist()

# --- 4. Initialize Ollama LLM (Llama 3.2) ---
print(f"Initializing LLM: {OLLAMA_LLM_MODEL}...")
llm = Ollama(model=OLLAMA_LLM_MODEL)
print("LLM ready.")

# --- 5. Set up the RAG Chain ---
print("Setting up RetrievalQA chain...")
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff", # 'stuff' combines all retrieved documents into one prompt
    retriever=vectorstore.as_retriever(search_kwargs={"k": 3}) # Retrieve top 3 relevant documents
)
print("RAG chain ready.")

# --- 6. Query the RAG System ---
print("\n--- Start Querying ---")
while True:
    query = input("Enter your query about proteins (or 'exit' to quit): ")
    if query.lower() == 'exit':
        break

    try:
        response = qa_chain.invoke({"query": query})
        print("\n--- Response ---")
        print(response["result"])
        print("----------------\n")
    except Exception as e:
        print(f"An error occurred: {e}")
        print("Please ensure Ollama server is running and models are downloaded.")

Loaded 100 documents from the CSV.
Initializing embedding model: mxbai-embed-large...
Creating/Loading Vector Store at: ./chroma_db...

C:\Users\rkuma\AppData\Local\Temp\ipykernel_11972\1258636114.py:58: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  vectorstore.persist()

Vector store ready.
Initializing LLM: llama3.2...
LLM ready.
Setting up RetrievalQA chain...
RAG chain ready.

--- Start Querying ---

Enter your query about proteins (or 'exit' to quit):  100d protein

--- Response ---
Based on the provided context, I don't know what the question about "100d protein" is. The text only provides information about three proteins (turkey egg lysozyme, magnesium ion, and bovine seminal ribonuclease) but does not mention a protein designated as "100d".
----------------

Enter your query about proteins (or 'exit' to quit):  100D

--- Response ---
I don't know the answer to the question 100D based on the provided context. The context only provides information about DNA structures, X-ray diffraction methods, and refinement algorithms for certain DNA sequences, but it does not mention any specific DNA sequence with an ID of "100D".
----------------

Enter your query about proteins (or 'exit' to quit):  exit

In [17]:
import pandas as pd
from langchain_community.document_loaders import CSVLoader
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import OllamaEmbeddings
from langchain_community.llms import Ollama
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate
import os

# --- Configuration ---
CSV_FILE_PATH = '100_data.csv' # Replace with your CSV file path
OLLAMA_EMBEDDING_MODEL = 'mxbai-embed-large' # Or 'nomic-embed-text', etc.
OLLAMA_LLM_MODEL = 'llama3.2'
VECTOR_DB_PATH = './chroma_db5' # Directory to store your vector database

# --- 1. Load and Process CSV Data ---
df = pd.read_csv(CSV_FILE_PATH)

df['rag_content'] = df.apply(
    lambda row: f"rcsb_id: {row['rcsb_id']}\n"
                f"pubmed_id: {row['pubmed_id']}\n"
                f"title: {row['title']}\n"
                f"PubMed Abstract: {row['PubMed Abstract']}\n"
                f"Ligand_name: {row['Ligand_name']}",
    axis=1
)

from langchain.schema import Document

documents = []
for index, row in df.iterrows():
    doc = Document(
        page_content=row['rag_content'],
        metadata={
            'source': CSV_FILE_PATH,
            'row_id': index,
            'rcsb_id': row['rcsb_id'],
        }
    )
    documents.append(doc)

print(f"Loaded {len(documents)} documents from the CSV.")

# --- 2. Initialize Ollama Embedding Model ---
print(f"Initializing embedding model: {OLLAMA_EMBEDDING_MODEL}...")
embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)

# --- 3. Create and Persist Vector Store (ChromaDB) ---
print(f"Creating/Loading Vector Store at: {VECTOR_DB_PATH}...")
# This will create a new ChromaDB or load an existing one
# If the directory exists, it will load; otherwise, it will create.
vectorstore = Chroma.from_documents(
    documents=documents,
    embedding=embeddings,
    persist_directory=VECTOR_DB_PATH
)
print("Vector store ready.")

# Persist the collection (optional, but good practice if you want to reuse)
vectorstore.persist()

# --- 4. Initialize Ollama LLM (Llama 3.2) ---
print(f"Initializing LLM: {OLLAMA_LLM_MODEL}...")
llm = Ollama(model=OLLAMA_LLM_MODEL)
print("LLM ready.")

# --- 5. Set up the RAG Chain with a custom prompt ---
print("Setting up RetrievalQA chain with custom prompt...")

# Define your custom prompt template
# This tells the LLM what its role is and how to use the context.
template = """Use the following context to answer the question.
If you don't know the answer, just say that you don't know, don't try to make up an answer.
You are a bioinformatics specialist and your task is to provide information about the proteins, based on the provided data.

Context:
{context}

Question: {question}
Helpful Answer:"""
QA_CHAIN_PROMPT = PromptTemplate.from_template(template)


qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vectorstore.as_retriever(search_kwargs={"k": 5}), # Increased k to 5, consider increasing if needed
    chain_type_kwargs={"prompt": QA_CHAIN_PROMPT}, # Pass the custom prompt here
    return_source_documents=True # Set to True to see what documents were retrieved
)
print("RAG chain ready.")

# --- 6. Query the RAG System ---
print("\n--- Start Querying ---")
while True:
    query = input("Enter your query about proteins (or 'exit' to quit): ")
    if query.lower() == 'exit':
        break

    try:
        response = qa_chain.invoke({"query": query})
        print("\n--- Response ---")
        print(response["result"])

        # Print the source documents to see what was retrieved
        if response.get("source_documents"):
            print("\n--- Source Documents Retrieved ---")
            for i, doc in enumerate(response["source_documents"]):
                print(f"Document {i+1} (Protein ID: {doc.metadata.get('rcsb_id', 'N/A')}):")
                print(doc.page_content[:200] + "...") # Print first 200 chars for brevity
                print("-" * 20)

        print("----------------\n")
    except Exception as e:
        print(f"An error occurred: {e}")
        print("Please ensure Ollama server is running and models are downloaded.")

Loaded 100 documents from the CSV.
Initializing embedding model: mxbai-embed-large...
Creating/Loading Vector Store at: ./chroma_db5...
Vector store ready.
Initializing LLM: llama3.2...
LLM ready.
Setting up RetrievalQA chain with custom prompt...
RAG chain ready.

--- Start Querying ---

Enter your query about proteins (or 'exit' to quit):  What is the title of 100D?

--- Response ---
I don't know the answer to that question. The provided data only includes information about proteins with RCSP IDs ranging from 101M to 104M, but not 100D.

--- Source Documents Retrieved ---
Document 1 (Protein ID: 109M):
rcsb_id: 109M
pubmed_id: is not available
title: SPERM WHALE MYOGLOBIN D122N ETHYL ISOCYANIDE AT PH 9.0
PubMed Abstract: is not available
Ligand_name: ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING FE'...
--------------------
Document 2 (Protein ID: 101M):
rcsb_id: 101M
pubmed_id: is not available
title: SPERM WHALE MYOGLOBIN F46V N-BUTYL ISOCYANIDE AT PH 9.0
PubMed Abstract: is not available
Ligand_name: ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING FE...
--------------------
Document 3 (Protein ID: 112M):
rcsb_id: 112M
pubmed_id: is not available
title: SPERM WHALE MYOGLOBIN D122N N-PROPYL ISOCYANIDE AT PH 9.0
PubMed Abstract: is not available
Ligand_name: ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING ...
--------------------
Document 4 (Protein ID: 111M):
rcsb_id: 111M
pubmed_id: is not available
title: SPERM WHALE MYOGLOBIN D122N N-BUTYL ISOCYANIDE AT PH 9.0
PubMed Abstract: is not available
Ligand_name: ['SULFATE ION', 'PROTOPORPHYRIN IX CONTAINING F...
--------------------
Document 5 (Protein ID: 104M):
rcsb_id: 104M
pubmed_id: is not available
title: SPERM WHALE MYOGLOBIN N-BUTYL ISOCYANIDE AT PH 7.0
PubMed Abstract: is not available
Ligand_name: ['SULFATE ION', 'N-BUTYL ISOCYANIDE', 'PROTOPORPHYRIN...
--------------------
----------------

KeyboardInterrupt: Interrupted by user

Enter your query about proteins (or 'exit' to quit):  exit

In [4]:
import pandas as pd
from langchain_community.document_loaders import CSVLoader
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import OllamaEmbeddings
from langchain_community.llms import Ollama
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate
import os

# --- Configuration ---
CSV_FILE_PATH = '100_data.csv' # Make sure this matches your CSV file name
OLLAMA_EMBEDDING_MODEL = 'mxbai-embed-large' # Or 'nomic-embed-text', etc.
OLLAMA_LLM_MODEL = 'llama3.2'
VECTOR_DB_PATH = './Chroma_db/chroma_db1' # Directory to store your vector database

# --- 1. Load and Process CSV Data ---
# Load the CSV file into a pandas DataFrame
df = pd.read_csv(CSV_FILE_PATH)

# Create a 'rag_content' column by combining relevant information from CSV columns.
# This concatenated string will be the primary content embedded for retrieval.
df['rag_content'] = df.apply(
    lambda row: f"rcsb_id: {row['rcsb_id']}\n"
                f"pubmed_id: {row['pubmed_id']}\n"
                f"title: {row['title']}\n"
                f"PubMed Abstract: {row['PubMed Abstract']}\n"
                f"Ligand_name: {row['Ligand_name']}",
    axis=1
)

# Convert DataFrame rows into LangChain Document objects.
# Each Document will contain the 'rag_content' and relevant metadata.
from langchain.schema import Document

documents = []
for index, row in df.iterrows():
    doc = Document(
        page_content=row['rag_content'],
        metadata={
            'source': CSV_FILE_PATH,
            'row_id': index,
            'rcsb_id': row['rcsb_id'], # Keep rcsb_id in metadata for easy access/filtering
        }
    )
    documents.append(doc)

print(f"Loaded {len(documents)} documents from the CSV.")

# --- 2. Initialize Ollama Embedding Model ---
print(f"Initializing embedding model: {OLLAMA_EMBEDDING_MODEL}...")
# This uses your local Ollama instance to generate embeddings.
embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)
print("Embedding model initialized.")

vectorstore = Chroma.from_documents(
    documents=documents,
    embedding=embeddings,
    persist_directory=VECTOR_DB_PATH
)
vectorstore.persist()
llm = Ollama(model=OLLAMA_LLM_MODEL)
print("LLM ready.")

template = """Use the following context to answer the question.
If you don't know the answer, just say that you don't know, don't try to make up an answer.
You are a bioinformatics specialist and your task is to provide information about the proteins, based on the provided data.

Context:
{context}

Question: {question}
Helpful Answer:"""
QA_CHAIN_PROMPT = PromptTemplate.from_template(template)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vectorstore.as_retriever(search_kwargs={"k": 5}),
    chain_type_kwargs={"prompt": QA_CHAIN_PROMPT},
    return_source_documents=True
)
print("RAG chain ready.")

# --- 6. Query the RAG System ---
print("\n--- Start Querying ---")
while True:
    query = input("Enter your query about proteins (or 'exit' to quit): ")
    if query.lower() == 'exit':
        break

    try:
        # Invoke the RAG chain with the user's query.
        response = qa_chain.invoke({"query": query})
        print("\n--- Response ---")
        print(response["result"])

        # Display the source documents that were retrieved and used to generate the answer.
        if response.get("source_documents"):
            print("\n--- Source Documents Retrieved ---")
            for i, doc in enumerate(response["source_documents"]):
                print(f"Document {i+1} (RCSB ID: {doc.metadata.get('rcsb_id', 'N/A')}):")
                # Print only the first 200 characters of the page_content for brevity
                print(doc.page_content[:200] + "...")
                print("-" * 20)

        print("----------------\n")
    except Exception as e:
        print(f"An error occurred: {e}")
        print("Please ensure Ollama server is running and models are downloaded.")

Loaded 100 documents from the CSV.
Initializing embedding model: mxbai-embed-large...
Embedding model initialized.
Creating/Loading Vector Store at: ./Chroma_db/chroma_db1...

C:\Users\rkuma\AppData\Local\Temp\ipykernel_19640\2003632279.py:52: LangChainDeprecationWarning: The class `OllamaEmbeddings` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the :class:`~langchain-ollama package and should be used instead. To use it run `pip install -U :class:`~langchain-ollama` and import as `from :class:`~langchain_ollama import OllamaEmbeddings``.
  embeddings = OllamaEmbeddings(model=OLLAMA_EMBEDDING_MODEL)
C:\Users\rkuma\AppData\Local\Temp\ipykernel_19640\2003632279.py:65: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  vectorstore.persist()
C:\Users\rkuma\AppData\Local\Temp\ipykernel_19640\2003632279.py:71: LangChainDeprecationWarning: The class `Ollama` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the :class:`~langchain-ollama package and should be used instead. To use it run `pip install -U :class:`~langchain-ollama` and import as `from :class:`~langchain_ollama import OllamaLLM``.
  llm = Ollama(model=OLLAMA_LLM_MODEL)

Vector store ready and persisted.
Initializing LLM: llama3.2...
LLM ready.
Setting up RetrievalQA chain with custom prompt...
RAG chain ready.

--- Start Querying ---

Enter your query about proteins (or 'exit' to quit):  what is the 100D

--- Response ---
I don't know the answer to your question about the "100D". Could you please provide more context or clarify what you are referring to? I'll do my best to help once I understand the question.

--- Source Documents Retrieved ---
Document 1 (RCSB ID: 119D):
rcsb_id: 119D
pubmed_id: 8230199.0
title: CRYSTAL AND MOLECULAR STRUCTURE OF D(CGTAGATCTACG) AT 2.25 ANGSTROMS RESOLUTION
PubMed Abstract: Single crystal X-ray diffraction methods have been used to de...
--------------------
Document 2 (RCSB ID: 117D):
rcsb_id: 117D
pubmed_id: 1480485.0
title: CRYSTAL AND MOLECULAR STRUCTURE OF THE ALTERNATING DODECAMER D(GCGTACGTACGC) IN THE A-DNA FORM: COMPARISON WITH THE ISOMORPHOUS NON-ALTERNATING DODECAMER D(CC...
--------------------
Document 3 (RCSB ID: 121D):
rcsb_id: 121D
pubmed_id: 8395202.0
title: MOLECULAR STRUCTURE OF THE A-TRACT DNA DODECAMER D(CGCAAATTTGCG) COMPLEXED WITH THE MINOR GROOVE BINDING DRUG NETROPSIN
PubMed Abstract: The molecular structu...
--------------------
Document 4 (RCSB ID: 11GS):
rcsb_id: 11GS
pubmed_id: 9426214.0
title: Glutathione s-transferase complexed with ethacrynic acid-glutathione conjugate (form ii)
PubMed Abstract: The diuretic drug ethacrynic acid, an inhibitor of p...
--------------------
Document 5 (RCSB ID: 115D):
rcsb_id: 115D
pubmed_id: 3271041.0
title: ORDERED WATER STRUCTURE IN AN A-DNA OCTAMER AT 1.7 ANGSTROMS RESOLUTION
PubMed Abstract: The crystal structure of the deoxyoctamer d(G-G-Br U-A-BrU-A-C-C) was...
--------------------
----------------

Enter your query about proteins (or 'exit' to quit):  exit